import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Language = "sw" | "en";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (english: string) => string;
};

const translations: Record<string, string> = {
  "Today": "Leo",
  "System administrator": "Msimamizi wa mfumo",
  "Human resources": "Rasilimali watu",
  "Store manager": "Msimamizi wa stoo",
  "General supervisor": "Msimamizi mkuu",
  "Assistant general supervisor": "Msaidizi wa msimamizi mkuu",
  "Zone supervisor": "Msimamizi wa kanda",
  "Site manager / supervisor": "Msimamizi wa eneo",
  "Management viewer": "Mtazamaji wa usimamizi",
  "HR onboarding": "Usajili wa wafanyakazi",
  "People registry": "Orodha ya watu",
  "Daily cleanliness": "Usafi wa kila siku",
  "Daily cleanliness worksheet": "Jedwali la usafi wa kila siku",
  "Daily Cleanliness Survey · Toilets / Vyooni": "UHAKIKI WA USAFI · VYOONI",
  "Daily Cleanliness Survey · Offices / Ofisini": "UHAKIKI WA USAFI · OFISINI",
  "Daily Cleanliness Survey · Indoor areas / Eneo la ndani": "UHAKIKI WA USAFI · ENEO LA NDANI",
  "Daily Cleanliness Survey · Outdoor areas / Eneo la nje": "UHAKIKI WA USAFI · ENEO LA NJE",
  "Daily Cleanliness Survey · Garden / Bustani": "UHAKIKI WA USAFI · BUSTANI",
  "Daily Cleanliness Survey · Store and equipment": "UHAKIKI WA USAFI · USIMAMIZI WA STORE NA VITENDEA KAZI",
  "Daily Cleanliness Survey · Store and equipment / Usimamizi wa store": "UHAKIKI WA USAFI · USIMAMIZI WA STORE NA VITENDEA KAZI",
  "Daily Cleanliness Survey · Staff performance": "UHAKIKI WA USAFI · MAENDELEO YA WAFANYAKAZI",
  "Daily Cleanliness Survey · Staff performance / Maendeleo ya wafanyakazi": "UHAKIKI WA USAFI · MAENDELEO YA WAFANYAKAZI",
  "PDF-derived daily cleanliness worksheet for Toilets / Vyooni.": "",
  "PDF-derived daily cleanliness worksheet for Offices / Ofisini.": "",
  "PDF-derived daily cleanliness worksheet for Indoor areas / Eneo la ndani.": "",
  "PDF-derived daily cleanliness worksheet for Outdoor areas / Eneo la nje.": "",
  "PDF-derived daily cleanliness worksheet for Garden / Bustani.": "",
  "PDF-derived daily cleanliness worksheet for Store and equipment / Usimamizi wa store.": "",
  "PDF-derived daily cleanliness worksheet for Staff performance / Maendeleo ya wafanyakazi.": "",
  "Answer the row and record an exception when the check is not complete.": "Jaza safu na andika tatizo kama halijakamilika.",
  "Stores & stock": "Stoo na vifaa",
  "Company inventory": "Mali za kampuni",
  "Store control": "Usimamizi wa stoo",
  "Supply operations": "Uendeshaji wa vifaa",
  "Manage company stores, products, stock transfers, opening balances, and usage evidence.": "Simamia stoo za kampuni, bidhaa, uhamisho wa stok, salio la mwanzo na kumbukumbu za matumizi.",
  "Store hierarchy": "Muundo wa stoo",
  "Super Store": "Stoo kuu",
  "Power Store": "Stoo ya usambazaji",
  "Site Store": "Stoo ya kituo",
  "Company product catalogue": "Orodha ya bidhaa za kampuni",
  "Products and units": "Bidhaa na vipimo",
  "Current unit cost": "Bei ya sasa kwa kipimo",
  "Create product": "Ongeza bidhaa",
  "Product name": "Jina la bidhaa",
  "Product code": "Namba ya bidhaa",
  "Unit of measure": "Kipimo",
  "Category": "Kundi",
  "Create store": "Unda stoo",
  "Store name": "Jina la stoo",
  "Store type": "Aina ya stoo",
  "Parent store": "Stoo inayosambaza",
  "Optional site": "Kituo (si lazima)",
  "Company products": "Bidhaa za kampuni",
  "Opening balance": "Salio la mwanzo",
  "Opening quantity": "Kiasi cha mwanzo",
  "Opening month": "Mwezi wa mwanzo",
  "Record opening balance": "Hifadhi salio la mwanzo",
  "Stock transfers": "Uhamisho wa stok",
  "Source item": "Bidhaa ya chanzo",
  "Destination item": "Bidhaa ya kupokea",
  "Transfer quantity": "Kiasi cha kuhamisha",
  "Record transfer": "Hifadhi uhamisho",
  "Weekly usage and value": "Matumizi na thamani ya wiki",
  "Quantity used": "Kiasi kilichotumika",
  "Value used": "Thamani iliyotumika",
  "No usage has been recorded for this period.": "Hakuna matumizi yaliyohifadhiwa katika kipindi hiki.",
  "Zone verified": "Imethibitishwa na msimamizi wa kanda",
  "Assistant approved": "Imeidhinishwa na msaidizi wa msimamizi mkuu",
  "HR packing": "Rasilimali watu wanapakia",
  "Assembled": "Imekusanywa",
  "Stock request workflow": "Mtiririko wa ombi la stok",
  "Site Supervisor submits → Zone Supervisor verifies → Assistant General Supervisor approves → HR packs and assembles.": "Msimamizi wa kituo anatuma → Msimamizi wa kanda anathibitisha → Msaidizi wa msimamizi mkuu anaidhinisha → Rasilimali watu wanapakia na kukusanya.",
  "Refresh inventory": "Sasisha mali",
  "No stores are configured yet.": "Hakuna stoo iliyowekwa bado.",
  "No company products are configured yet.": "Hakuna bidhaa za kampuni zilizowekwa bado.",
  "Request configured stock": "Omba stok iliyowekwa",
  "Prepare this month’s request": "Andaa ombi la mwezi huu",
  "Review stock requests": "Kagua maombi ya stok",
  "Stock request submitted": "Ombi la stok limetumwa",
  "Request status updated": "Hatua ya ombi imesasishwa",
  "Verify request": "Thibitisha ombi",
  "Approve request": "Idhinisha ombi",
  "Start packing": "Anza kupakia",
  "Mark assembled": "Weka kuwa imekusanywa",
  "The monthly request window closed after the 17th. Your submitted request remains available for review.": "Muda wa ombi la mwezi umefungwa baada ya tarehe 17. Ombi lako lililotumwa bado linaweza kukaguliwa.",
  "Assigned store": "Stoo uliyopewa",
  "Item": "Bidhaa",
  "Unit": "Kipimo",
  "Quantity left": "Kiasi kilichobaki",
  "Quantity requested": "Kiasi kinachoombwa",
  "Request notes": "Maelezo ya ombi",
  "Submit stock request": "Tuma ombi la stok",
  "Choose a site store then use the request action shown beside each itemised request in your queue.": "Chagua stoo ya kituo kisha tumia kitendo kinachoonekana kwenye kila ombi la bidhaa katika foleni yako.",
  "Request history": "Historia ya maombi",
  "Stock requests": "Maombi ya stok",
  "Select a store to begin": "Chagua stoo kuanza",
  "Only requests inside your authorised scope are shown.": "Ni maombi yaliyo ndani ya eneo lako la ruhusa pekee yanaonyeshwa.",
  "No requests for this store": "Hakuna maombi kwa stoo hii",
  "Submitted requests will appear here with their complete approval trail.": "Maombi yaliyotumwa yataonekana hapa pamoja na hatua zote za idhini.",
  "Request": "Ombi",
  "No notes": "Hakuna maelezo",
  "left": "kilichobaki",
  "verified": "kimethibitishwa",
  "approved": "kimeidhinishwa",
  "Loading configured stores": "Inapakia stoo zilizowekwa",
  "Add another item": "Ongeza bidhaa nyingine",
  "Individual onboarding": "Usajili wa mtu mmoja",
  "Register one cleaner": "Sajili msafi mmoja",
  "Record identity and contact information now. Each new cleaner starts as a trainee and can be assigned to a site afterward.": "Weka taarifa za utambulisho na mawasiliano sasa. Kila msafi mpya huanza kama mwanafunzi na anaweza kupewa kituo baadaye.",
  "First name": "Jina la kwanza",
  "Last name": "Jina la mwisho",
  "ID type": "Aina ya kitambulisho",
  "ID number": "Namba ya kitambulisho",
  "Birth date": "Tarehe ya kuzaliwa",
  "Gender": "Jinsia",
  "Not specified": "Haijatajwa",
  "Female": "Mwanamke",
  "Male": "Mwanaume",
  "Other": "Nyingine",
  "Living location": "Mahali anapoishi",
  "Phone number": "Namba ya simu",
  "Emergency contact": "Mtu wa dharura",
  "Contact name": "Jina la mawasiliano",
  "Relationship": "Uhusiano",
  "Contact phone": "Simu ya mawasiliano",
  "Register cleaner": "Sajili msafi",
  "Cleaner registered as trainee. Continue with site assignment and trainee programme setup.": "Msafi amesajiliwa kama mwanafunzi. Endelea na ugawaji wa kituo na kuanzisha programu ya mafunzo.",
  "Administration": "Usimamizi",
  "Users & roles": "Watumiaji na nafasi",
  "Sites, zones & GIS": "Maeneo, kanda na ramani",
  "Integration settings": "Mipangilio ya miunganisho",
  "Sites & zones": "Maeneo na kanda",
  "Assignments & shifts": "Ugawaji na zamu",
  "Trainee management": "Usimamizi wa wanafunzi",
  "Attendance": "Mahudhurio",
  "Monthly remuneration": "Malipo ya kila mwezi",
  "Monthly remuneration audit": "Ukaguzi wa malipo wa kila mwezi",
  "Supervisor timetables": "Ratiba za wasimamizi",
  "My timetable": "Ratiba yangu",
  "Create supervisor timetable": "Unda ratiba ya msimamizi",
  "Manage supervisor timetables": "Simamia ratiba za wasimamizi",
  "Create, review, activate, deactivate, or safely remove personal, auditable supervisor schedules.": "Unda, kagua, washa, zima au ondoa kwa usalama ratiba binafsi za wasimamizi zenye kumbukumbu ya ukaguzi.",
  "Add timetable": "Ongeza ratiba",
  "Refresh timetable data": "Sasisha taarifa za ratiba",
  "Loading timetable data": "Inapakia taarifa za ratiba",
  "Step": "Hatua",
  "Choose scope": "Chagua aina ya msimamizi",
  "Choose supervisors": "Chagua wasimamizi",
  "Choose zones and sites": "Chagua kanda na vituo",
  "Schedule details": "Maelezo ya ratiba",
  "Review": "Kagua",
  "Supervisor scope": "Aina ya msimamizi",
  "Select whether this timetable is for a Zone Supervisor who visits sites or an Assistant General Supervisor who visits zones.": "Chagua kama ratiba ni ya Msimamizi wa Kanda anayekagua vituo au Msaidizi wa Msimamizi Mkuu anayekagua kanda.",
  "Select specific supervisors": "Chagua wasimamizi mahususi",
  "Only active assignments are shown. You may choose more than one supervisor when their assignments match the planned visits.": "Ni ugawaji unaofanya kazi tu unaoonyeshwa. Unaweza kuchagua wasimamizi zaidi ya mmoja kama ugawaji wao unaendana na ziara zilizopangwa.",
  "No active supervisor assignments are available for this scope.": "Hakuna ugawaji hai wa wasimamizi kwa aina hii.",
  "Assigned zones": "Kanda alizopewa",
  "All zones": "Kanda zote",
  "Select operational zones": "Chagua kanda za kazi",
  "Select the zones this timetable covers. Supervisors receive entries only for sites inside their current assignment scope.": "Chagua kanda ambazo ratiba hii inahusu. Wasimamizi hupata ratiba za vituo vilivyomo kwenye eneo lao la kazi walilopewa kwa sasa.",
  "Select sites": "Chagua vituo",
  "Choose the specific sites visited by the Zone Supervisor.": "Chagua vituo mahususi vitakavyotembelewa na Msimamizi wa Kanda.",
  "Optionally select sites to focus an Assistant General Supervisor’s zone visit. Leave all sites unselected to include every active site in the chosen zones.": "Kwa hiari chagua vituo vya kuzingatia kwenye ziara ya kanda ya Msaidizi wa Msimamizi Mkuu. Acha vituo vyote bila kuchaguliwa ili kujumuisha vituo vyote vinavyofanya kazi kwenye kanda ulizochagua.",
  "No active sites are configured in this zone.": "Hakuna vituo vinavyofanya kazi vilivyowekwa kwenye kanda hii.",
  "Schedule title": "Jina la ratiba",
  "For example: Week one site visits": "Mfano: Ziara za wiki ya kwanza",
  "Effective from": "Tarehe ya kuanza",
  "Effective to (optional)": "Tarehe ya mwisho (si lazima)",
  "Work days": "Siku za kazi",
  "Off days": "Siku za mapumziko",
  "Shift": "Zamu",
  "Morning": "Asubuhi",
  "Afternoon": "Mchana",
  "Full day": "Siku nzima",
  "Notes": "Maelezo",
  "Add useful instructions for the supervisor.": "Ongeza maelekezo muhimu kwa msimamizi.",
  "Review before saving": "Kagua kabla ya kuhifadhi",
  "Selected supervisors": "Wasimamizi waliochaguliwa",
  "Selected zones": "Kanda zilizochaguliwa",
  "Selected sites": "Vituo vilivyochaguliwa",
  "All active sites in selected zones": "Vituo vyote vinavyofanya kazi kwenye kanda zilizochaguliwa",
  "Save timetable": "Hifadhi ratiba",
  "Back": "Rudi",
  "Continue": "Endelea",
  "Timetable saved. {count} personal schedule entries were created.": "Ratiba imehifadhiwa. Rekodi {count} za ratiba binafsi zimeundwa.",
  "All timetables": "Ratiba zote",
  "Review every timetable, including inactive records retained for audit history.": "Kagua kila ratiba, ikiwemo rekodi zisizofanya kazi zilizohifadhiwa kwa historia ya ukaguzi.",
  "Supervisor": "Msimamizi",
  "Scope": "Aina",
  "Zone": "Kanda",
  "Site": "Kituo",
  "Days": "Siku",
  "Status": "Hali",
  "Actions": "Hatua",
  "Active": "Inafanya kazi",
  "Inactive": "Imesimamishwa",
  "Activate": "Washa",
  "Deactivate": "Zima",
  "Delete": "Ondoa",
  "No timetables have been created yet.": "Bado hakuna ratiba iliyoundwa.",
  "The timetable was retained as inactive because checklist history depends on it.": "Ratiba imehifadhiwa ikiwa imesimamishwa kwa sababu historia ya ukaguzi inaitegemea.",
  "The timetable was deleted.": "Ratiba imeondolewa.",
  "Unable to complete the timetable action.": "Imeshindikana kukamilisha hatua ya ratiba.",
  "Personal timetable": "Ratiba binafsi",
  "My site visit timetable": "Ratiba yangu ya ziara za vituo",
  "My zone visit timetable": "Ratiba yangu ya ziara za kanda",
  "View only your own approved schedule by day, week, or month.": "Angalia ratiba yako iliyoidhinishwa pekee kwa siku, wiki au mwezi.",
  "Day": "Siku",
  "Week": "Wiki",
  "Previous period": "Kipindi kilichopita",
  "Next period": "Kipindi kinachofuata",
  "No timetable is scheduled for this period.": "Hakuna ratiba iliyopangwa kwa kipindi hiki.",
  "Your System Administrator can assign a personal timetable for your current zones or sites.": "Msimamizi wa mfumo anaweza kukupangia ratiba binafsi kwa kanda au vituo ulivyopewa.",
  "Site / zone": "Kituo / kanda",
  "Schedule": "Ratiba",
  "Schedule period": "Kipindi cha ratiba",
  "Ongoing": "Inaendelea",
  "Click a schedule card to view its details.": "Bonyeza kadi ya ratiba kuona maelezo yake.",
  "Morning shifts are green, afternoon shifts are gold, and full-day shifts are blue.": "Zamu za asubuhi ni kijani, za mchana ni dhahabu, na za siku nzima ni bluu.",
  "Monday": "Jumatatu",
  "Tuesday": "Jumanne",
  "Wednesday": "Jumatano",
  "Thursday": "Alhamisi",
  "Friday": "Ijumaa",
  "Saturday": "Jumamosi",
  "Sunday": "Jumapili",
  "My supervision checklist": "Orodha yangu ya ukaguzi",
  "Remuneration form": "Fomu ya malipo",
  "Monthly payment form": "Fomu ya malipo ya kila mwezi",
  "Employee information for payment": "Taarifa za wafanyakazi kwa ajili ya malipo",
  "From the 15th to the 25th, check the pre-filled attendance. Leave the new phone or PBZ account blank when it has not changed.": "Kuanzia tarehe 15 hadi 25, kagua mahudhurio yaliyowekwa tayari. Acha namba mpya ya simu au PBZ wazi kama haijabadilika.",
  "Choose site": "Chagua kituo",
  "Open form": "Fungua fomu",
  "The remuneration window is open from the 15th through the 25th.": "Dirisha la malipo liko wazi kuanzia tarehe 15 hadi 25.",
  "The remuneration window is closed. The form cannot be changed outside the 15th–25th window.": "Dirisha la malipo limefungwa. Fomu haiwezi kubadilishwa nje ya tarehe 15–25.",
  "Site name": "Jina la kituo",
  "Month": "Mwezi",
  "Cleaner name": "Jina la msafi",
  "Present days": "Siku alizohudhuria",
  "Days absent from work": "Siku aliyokosekana kazini",
  "Start date (new cleaner only)": "Tarehe alianza kazi (mfanyakazi mpya tu)",
  "Yas/Zantel phone number": "Namba ya simu Yas/Zantel",
  "PBZ account number": "Namba ya akaunti PBZ",
  "System attestation": "Sahihi ya mfumo",
  "Last approved": "Iliyoidhinishwa mwisho",
  "Not set": "Haijawekwa",
  "Leave blank when unchanged": "Acha wazi kama haijabadilika",
  "Save decision": "Hifadhi uamuzi",
  "Save draft": "Hifadhi rasimu",
  "Submit form": "Wasilisha fomu",
  "Submitted": "Imewasilishwa",
  "Draft": "Rasimu",
  "Returned": "Imerudishwa",
  "Reviewed": "Imekaguliwa",
  "The form has been submitted for HR/System Administrator review.": "Fomu imewasilishwa kwa ukaguzi wa HR/Msimamizi wa mfumo.",
  "If a new value is blank, the system uses the last approved payment contact. Any entered replacement goes to HR/System Administrator for review.": "Kama namba mpya imeachwa wazi, mfumo hutumia mawasiliano ya malipo yaliyoidhinishwa mwisho. Mabadiliko yoyote hutumwa HR/Msimamizi wa mfumo kwa ukaguzi.",
  "No assigned sites": "Hakuna kituo ulichopewa",
  "Ask a System Administrator to confirm your site assignment.": "Wasiliana na msimamizi wa mfumo kuthibitisha ugawaji wako wa kituo.",
  "Loading your sites": "Inapakia vituo vyako",
  "No form opened": "Fomu haijafunguliwa",
  "Choose a month and open the form for this site.": "Chagua mwezi na ufungue fomu ya kituo hiki.",
  "All-site remuneration audit": "Ukaguzi wa malipo wa vituo vyote",
  "Review every active cleaner’s monthly attendance, payment-contact history, proposed updates, and accountable audit trail.": "Kagua mahudhurio ya kila mwezi, historia ya mawasiliano ya malipo, mabadiliko yaliyopendekezwa, na kumbukumbu ya uwajibikaji ya kila msafi anayefanya kazi.",
  "All sites": "Vituo vyote",
  "Previous phone": "Simu ya awali",
  "Previous PBZ account": "Akaunti PBZ ya awali",
  "New phone": "Simu mpya",
  "New PBZ account": "Akaunti PBZ mpya",
  "Change state": "Hali ya mabadiliko",
  "Saved by": "Aliyehifadhi",
  "Saved at": "Muda wa kuhifadhi",
  "Form status": "Hali ya fomu",
  "Prepared by": "Aliyetayarisha",
  "Submitted at": "Muda wa kuwasilisha",
  "Reviewed by": "Aliyekagua",
  "Reviewed at": "Muda wa ukaguzi",
  "Loading monthly audit": "Inapakia ukaguzi wa kila mwezi",
  "No cleaner rows for this month": "Hakuna mistari ya wasafi kwa mwezi huu",
  "Inspections": "Ukaguzi",
  "Issues & jobs": "Matatizo na kazi",
  "Reports": "Ripoti",
  "Notifications": "Taarifa",
  "Messages": "Ujumbe",
  "New message": "Ujumbe mpya",
  "Search messages": "Tafuta ujumbe",
  "No messages yet": "Hakuna ujumbe bado",
  "No conversations": "Hakuna mazungumzo",
  "Start a secure conversation with an authorised contact.": "Anza mazungumzo salama na mtu unayeruhusiwa kuwasiliana naye.",
  "members": "wanachama",
  "Secure direct conversation": "Mazungumzo salama ya moja kwa moja",
  "Live": "Moja kwa moja",
  "You": "Wewe",
  "Voice message": "Ujumbe wa sauti",
  "Attach file": "Ambatanisha faili",
  "Write a message": "Andika ujumbe",
  "Documents, PDFs, images and voice messages stay private and are recorded in the audit trail.": "Nyaraka, PDF, picha na sauti hubaki binafsi na huandikwa kwenye kumbukumbu ya ukaguzi.",
  "Choose a conversation": "Chagua mazungumzo",
  "Select a conversation on the left or start a new secure message.": "Chagua mazungumzo upande wa kushoto au anza ujumbe mpya salama.",
  "New group": "Kikundi kipya",
  "Only authorised contacts are shown for your role.": "Unaonyeshwa watu unaoruhusiwa kuwasiliana nao kwa nafasi yako.",
  "Direct": "Moja kwa moja",
  "Group": "Kikundi",
  "Group name": "Jina la kikundi",
  "No authorised contacts are available right now.": "Hakuna mtu unayeruhusiwa kuwasiliana naye kwa sasa.",
  "Cancel": "Ghairi",
  "Start conversation": "Anza mazungumzo",
  "Account & security": "Akaunti na usalama",
  "Report archive": "Jalada la ripoti",
  "Operations": "Kazi za kila siku",
  "Workspace": "Eneo la kazi",
  "Your current scope": "Eneo lako la kazi",
  "Your accessible sites and actions are controlled by the White Bird policy layer.": "Maeneo na kazi unazoruhusiwa zinaongozwa na kanuni za White Bird.",
  "Refresh": "Sasisha",
  "Good day": "Habari",
  "Role command centre": "Kituo cha kazi",
  "Visible sites": "Maeneo yanayoonekana",
  "Active sites": "Maeneo yanayofanya kazi",
  "Open issues": "Matatizo yaliyo wazi",
  "Overdue jobs": "Kazi zilizochelewa",
  "Low-stock items": "Vifaa vilivyopungua",
  "Attendance rate": "Asilimia ya mahudhurio",
  "Reports awaiting action": "Ripoti zinazosubiri hatua",
  "Cleaners": "Wasafi",
  "Live from your permitted operational scope": "Taarifa za moja kwa moja kutoka eneo lako la kazi",
  "Building your operational picture": "Tunatayarisha muhtasari wa kazi zako",
  "Your metrics will appear here": "Vipimo vyako vitaonekana hapa",
  "Signals needing attention": "Taarifa zinazohitaji uangalifu",
  "View all": "Ona zote",
  "No unread operational signals are available.": "Hakuna taarifa mpya za kazi kwa sasa.",
  "Work in motion": "Kazi zinazoendelea",
  "Choose the next responsible action.": "Chagua hatua inayofuata ya kufanya.",
  "Role-aware": "Kulingana na nafasi yako",
  "Reporting chain": "Mfuatano wa ripoti",
  "Keep the handover moving.": "Endeleza makabidhiano ya kazi.",
  "Open reporting workspace": "Fungua eneo la ripoti",
  "Daily cleanliness declaration": "Taarifa ya usafi wa kila siku",
  "Complete today’s site sheet, one clear row at a time.": "Jaza fomu ya leo, mstari mmoja kwa wakati.",
  "Assigned site": "Eneo ulilopangiwa",
  "Date": "Tarehe",
  "Question / check": "Swali / ukaguzi",
  "Done on time": "Imekamilika kwa wakati",
  "Exception": "Tatizo / haijakamilika",
  "Evidence / responsible cleaner": "Maelezo / msafi anayehusika",
  "Save": "Hifadhi",
  "Saved": "Imehifadhiwa",
  "Submit area": "Wasilisha eneo",
  "Open area": "Fungua eneo",
  "Open today's sheet": "Fungua jedwali la leo",
  "Daily worksheet progress": "Maendeleo ya jedwali la leo",
  "questions answered": "maswali yamejibiwa",
  "areas submitted": "maeneo yamewasilishwa",
  "How to use this sheet:": "Jinsi ya kutumia jedwali hili:",
  "Answer each row, save it, and submit the area when all rows are complete.": "Jibu kila mstari, hifadhi, kisha wasilisha eneo baada ya mistari yote kukamilika.",
  "No daily cleanliness templates configured": "Hakuna fomu za usafi wa kila siku zilizowekwa",
  "Ask an administrator to configure daily templates.": "Muombe msimamizi aweke fomu za kila siku.",
  "Loading daily surveys": "Inapakia tafiti za kila siku",
  "Today's cleanliness sheet is open.": "Jedwali la usafi la leo limefunguliwa.",
  "Daily survey calendar": "Kalenda ya tafiti za kila siku",
  "Choose a day to review site surveys": "Chagua siku kuona tafiti za eneo",
  "Previous month": "Mwezi uliopita",
  "Next month": "Mwezi unaofuata",
  "Selected day": "Siku iliyochaguliwa",
  "No survey is open for this day": "Hakuna utafiti uliofunguliwa kwa siku hii",
  "Not opened": "Haijafunguliwa",
  "questions saved": "maswali yamehifadhiwa",
  "Choose another day or open a daily worksheet to begin.": "Chagua siku nyingine au fungua jedwali la kila siku kuanza.",
  "answers recorded": "majibu yamehifadhiwa",
  "Daily survey": "Utafiti wa kila siku",
  "daily declaration": "taarifa ya kila siku",
  "Open today’s sheet": "Fungua fomu ya leo",
  "Saved answers stay auditable.": "Majibu yaliyohifadhiwa yanaonekana kwenye kumbukumbu ya ukaguzi.",
  "This answer was already saved. The worksheet is now synchronized with the server record.": "Jibu hili lilikuwa tayari limehifadhiwa. Fomu sasa imesawazishwa na rekodi ya seva.",
  "declaration submitted for review.": "imetumwa kwa ukaguzi.",
  "What happened and what must happen next?": "Nini kimetokea na hatua gani ifuatayo inahitajika?",
  "Area": "Eneo",
  "Operational area": "Eneo la kazi",
  "Select assigned site": "Chagua eneo ulilopangiwa",
  "Once the dashboard service is connected and returns data for your role, White Bird will show only the KPIs you are permitted to see.": "Huduma ya dashibodi ikiunganishwa, White Bird itaonyesha vipimo unavyoruhusiwa kuona.",
  "Yes": "Ndiyo",
  "No": "Hapana",
  "No exception note required.": "Hakuna maelezo ya tatizo yanayohitajika.",
  "Select responsible cleaner": "Chagua msafi anayehusika",
  "Save answer": "Hifadhi jibu",
  "Save exception": "Hifadhi tatizo",
  "Refresh sheet": "Sasisha fomu",
  "Choose Done on time or Exception before saving.": "Chagua Imekamilika au Tatizo kabla ya kuhifadhi.",
  "Add a corrective note for this exception.": "Andika hatua ya kurekebisha tatizo hili.",
  "Loading today’s questions and assigned cleaners": "Tunapakia maswali ya leo na wasafi waliopangiwa",
  "Loading assigned cleanliness scope": "Tunapakia eneo lako la usafi",
  "Open this area to load its daily questions into the worksheet.": "Fungua eneo hili ili kupakia maswali yake ya leo.",
  "MENGINEYO / CHANGAMOTO ZILIZOJITOKEZA": "MENGINEYO / CHANGAMOTO ZILIZOJITOKEZA",
  "Orodhesha changamoto zilizojitokeza": "Orodhesha changamoto zilizojitokeza",
  "Changamoto": "Changamoto",
  "Hifadhi changamoto": "Hifadhi changamoto",
  "Changamoto zimehifadhiwa.": "Changamoto zimehifadhiwa.",
  "Hifadhiwa kwenye historia ya ripoti ya kila siku.": "Hifadhiwa kwenye historia ya ripoti ya kila siku.",
  "Inaokoa...": "Inaokoa...",
  "English": "Kiingereza",
  "Kiswahili": "Kiswahili",
  "Language": "Lugha",
  "Quick action": "Hatua ya haraka",
  "Fast track": "Njia ya haraka",
  "Start an authorised task": "Anza kazi iliyoruhusiwa",
  "Record today’s attendance": "Weka mahudhurio ya leo",
  "Complete daily cleanliness": "Jaza usafi wa leo",
  "Raise an issue or job": "Wasilisha tatizo au kazi",
  "Start an inspection": "Anza ukaguzi",
  "Onboard cleaners": "Sajili wasafi",
  "Trainee qualification": "Uthibitisho wa mwanafunzi",
  "HR reporting": "Ripoti za HR",
  "Requests to fulfill": "Maombi ya kutimiza",
  "Supply reporting": "Ripoti za vifaa",
  "Governance evidence": "Ushahidi wa usimamizi",
  "Stock control": "Udhibiti wa vifaa",
  "The workday starts with the right stock in the right place.": "Siku ya kazi huanza vifaa sahihi vikiwa mahali sahihi.",
  "Configure the platform so every team can execute clearly.": "Weka mfumo ili kila timu ifanye kazi kwa uwazi.",
  "People move forward when every gate is visible.": "Wafanyakazi huendelea vizuri kila hatua inapoonekana.",
  "Own the cleaner lifecycle, trainee evidence, and workforce assignment integrity.": "Simamia safari ya msafi, ushahidi wa mwanafunzi, na ugawaji sahihi wa wafanyakazi.",
  "Own the configured stock chain from count to fulfillment and movement evidence.": "Simamia vifaa kutoka kuhesabu hadi kutimiza mahitaji na kumbukumbu za matumizi.",
  "Keep users, sites, zones, shifts, and permissions governed from one administration boundary.": "Simamia watumiaji, maeneo, kanda, zamu, na ruhusa kutoka sehemu moja.",
  "Your workspace brings together the most important operational signals for the scope you are trusted to manage.": "Eneo lako la kazi linaonyesha taarifa muhimu za maeneo unayoruhusiwa kusimamia.",
  "Register individuals or preview a validated HR workbook.": "Sajili mtu au kagua faili la HR lililothibitishwa.",
  "Review evaluations, due dates, and final evidence.": "Kagua tathmini, tarehe muhimu, na ushahidi wa mwisho.",
  "Maintain workforce placement and shift integrity.": "Dumisha ugawaji wa wafanyakazi na usahihi wa zamu.",
  "Review workforce handover and documentation gaps.": "Kagua makabidhiano ya wafanyakazi na mapungufu ya nyaraka.",
  "Process configured inventory and supply risks.": "Shughulikia vifaa vilivyowekwa na hatari za upungufu.",
  "Review site needs and keep quantities accountable.": "Kagua mahitaji ya eneo na linda usahihi wa idadi.",
  "Track stock movements, requests, and exceptions.": "Fuatilia matumizi ya vifaa, maombi, na matatizo.",
  "Configure users, roles, sites, zones, and shifts.": "Weka watumiaji, nafasi, maeneo, kanda, na zamu.",
  "Maintain the operating estate and zone relationships.": "Dumisha maeneo ya kazi na uhusiano wa kanda.",
  "Review audit and reporting health.": "Kagua afya ya kumbukumbu na ripoti.",
  "Record, submit, or review today’s site attendance.": "Weka, wasilisha, au kagua mahudhurio ya leo.",
  "Complete evidence-led field checks and reviews.": "Kamilisha ukaguzi wa maeneo kwa ushahidi.",
  "Move priority work through verification and closure.": "Pelega kazi muhimu hadi kuthibitishwa na kufungwa.",
  "Review low-stock signals and supply requests.": "Kagua ishara za upungufu na maombi ya vifaa.",
  "Site reports, zone summaries, and management visibility follow a deliberate reviewed sequence.": "Ripoti za maeneo na muhtasari wa kanda hupitia hatua ya ukaguzi iliyo wazi.",
  "No reporting status is currently available for this scope.": "Hakuna hali ya ripoti inayopatikana kwa eneo hili kwa sasa.",
  "Operational signal layers": "Tabaka za taarifa za kazi",
  "Trend endpoints, ready for your scope.": "Mwelekeo wa kazi kwa eneo lako.",
  "Attendance trend": "Mwelekeo wa mahudhurio",
  "Issue categories": "Aina za matatizo",
  "Inspection quality": "Ubora wa ukaguzi",
  "Live data appears when its dashboard endpoint is connected.": "Taarifa halisi zitaonekana huduma ya dashibodi ikiunganishwa.",
  "Charts respect both role permissions and the visible site scope supplied by White Bird.": "Michoro inaheshimu nafasi yako na maeneo yanayoonekana kwenye White Bird.",
  "Source data only · no fabricated results": "Taarifa halisi tu · hakuna matokeo ya kutengenezwa",
  "Lobby": "ENEO LA NDANI",
  "Rooms": "ENEO LA NDANI",
  "Pool Deck": "ENEO LA NJE",
  "Toilet facilities": "VYOONI",
  "Garden and grounds": "BUSTANI",
  "Reception and entrance": "ENEO LA NDANI",
  "Shared and public areas": "ENEO LA NJE",
  "Daily Cleanliness Survey": "TAARIFA YA USAFI",
  "Daily Cleanliness Survey · Rooms": "UHAKIKI WA USAFI · ENEO LA NDANI",
  "Daily Cleanliness Survey · Pool Deck": "UHAKIKI WA USAFI · ENEO LA NJE",
  "Daily Cleanliness Survey · Toilet facilities": "UHAKIKI WA USAFI · VYOONI",
  "Daily Cleanliness Survey · Garden and grounds": "UHAKIKI WA USAFI · BUSTANI",
  "Daily Cleanliness Survey · Reception and entrance": "UHAKIKI WA USAFI · ENEO LA NDANI",
  "Daily Cleanliness Survey · Shared and public areas": "UHAKIKI WA USAFI · ENEO LA NJE",
  "Daily Cleanliness Survey · Lobby": "UHAKIKI WA USAFI · ENEO LA NDANI",
  "Ready-made daily cleanliness survey for operational site review.": "Uchunguzi wa usafi wa kila siku uliotayarishwa kwa ukaguzi wa eneo la kazi.",
  "Area cleaned to the agreed schedule": "Eneo limesafishwa kwa ratiba iliyokubaliwa",
  "Was the area completed within the required service window?": "Je, eneo limekamilishwa ndani ya muda uliopangwa wa huduma?",
  "High-touch surfaces cleaned": "Sehemu zinazoguswa mara kwa mara zimesafishwa",
  "Check doors, handles, switches, rails, and other high-touch surfaces.": "Kagua milango, vishikio, swichi, reli, na sehemu nyingine zinazoguswa mara kwa mara.",
  "Waste removed and bins reset": "Taka zimeondolewa na mapipa yamepangwa upya",
  "Confirm waste has been removed and bins are clean and correctly lined.": "Thibitisha taka zimeondolewa na mapipa ni safi na yana mifuko vizuri.",
  "Consumables and hygiene supplies available": "Vifaa vya matumizi na usafi vinapatikana",
  "Check soap, tissue, paper products, and other configured consumables.": "Kagua sabuni, tissue, karatasi, na vifaa vingine vilivyowekwa.",
  "Exception details and corrective action": "Maelezo ya tatizo na hatua ya kurekebisha",
  "Text answer": "Jibu la maandishi",
  "Write your answer": "Andika jibu lako",
  "Write an answer before saving.": "Andika jibu kabla ya kuhifadhi.",
  "If any item failed, record who is responsible, what was done, and the next review time.": "Kama kuna jambo halijakamilika, andika anayehusika, kilichofanyika, na muda wa ukaguzi unaofuata.",
  "Toilets / Vyooni": "VYOONI",
  "Offices / Ofisini": "OFISINI",
  "Indoor areas / Eneo la ndani": "ENEO LA NDANI",
  "Outdoor areas / Eneo la nje": "ENEO LA NJE",
  "Garden / Bustani": "BUSTANI",
  "Store and equipment / Usimamizi wa store": "USIMAMIZI WA STORE NA VITENDEA KAZI",
  "Staff performance / Maendeleo ya wafanyakazi": "MAENDELEO YA WAFANYAKAZI",
  "Floor and wall surfaces have been washed and cleaned": "Sakafu zimesafishwa na kukaushwa",
  "Mirrors have been cleaned": "Vioo Vimesafishwa",
  "Rubbish bin has been cleaned": "Taka zimewagwa na dustin kusafishwa",
  "Toilet has been washed and cleaned": "Masinki na matoleo ya maji yamesafishwa na kusuguliwa",
  "Soap, brushes, and cleaning tools are washed and stored properly": "Manukato yamewekwa",
  "Water has been put into the cleaning tank": "Maji yamekaushwa na kuta na sakafu zimesafishwa.",
  "Water has been put into the hand-washing container": "Maji yamekaushwa na kuta na sakafu zimesafishwa.",
  "Towels have been placed": "Manukato yamewekwa",
  "Toilet paper has been placed": "Toilet paper zimewekwa",
  "Floor and wall surfaces have been cleaned": "Sakafu imesafishwa na kukaushwa kila mara.",
  "Chairs, tables, and office equipment have been dusted": "Viti, meza, makabati vimefutwa vumbi na kusafishwa sehemu zote",
  "Rubbish bin has been washed and cleaned": "Dustibini imetolewa taka na kusafishwa",
  "Desk has been arranged and cleaned": "Vitu vimesogezwa kusafishwa na kurudishwa sehemu yake",
  "Floors, doors, and windows have been cleaned": "Milango,Paa, Madirsha na vioo vimesafishwa",
  "Floors and doors have been cleaned": "Sakafu imesafishwa na kukaushwa kila mara.",
  "Tables have been arranged and curtains straightened": "Vitu vimesogezwa kusafishwa na kurudishwa sehemu yake",
  "Ceiling has been wiped and cobwebs removed": "Tandabui zimetolewa, Na vifaa vimefutwa vumbi.",
  "Furniture has been arranged": "Vitu vimesogezwa kusafishwa na kurudishwa sehemu yake",
  "Rubbish bin has been placed": "Dustibini imetolewa taka na kusafishwa",
  "Stairs have been cleaned before opening": "Ngazi na sehemu za mashikio zimesafishwa kwa kurudiwa",
  "Entrance has been wiped and cleaned": "Milango,Paa, Madirsha na vioo vimesafishwa",
  "Furniture has been arranged and curtains straightened": "Vitu vimesogezwa kusafishwa na kurudishwa sehemu yake",
  "Bin has been placed": "Je manukato yamewekwa.",
  "Water has been put in the water container and it has been covered": "Dawa ya kuua wadudu zimewekwa/kupuliziwa",
  "Grass has been cut": "Kupogoa na Kupunguza",
  "Parking area has been cleaned": "Maeneo ya kukaa yamesafishwa",
  "Fence has been cleaned": "Viambaza vimesafishwa",
  "Paths and passages have been cleaned": "Njia za kutembelea zimesafishwa",
  "All surrounding areas have been cleaned": "Maeneo yaliyoificha yamesafishwa",
  "Outdoor area has been watered": "Kumwagilia",
  "Rubbish bin has been wiped and cleaned": "Dustibini zimetolewa taka na kusafishwa",
  "Flower beds have been watered": "Kumwagilia",
  "Flowers have been pruned": "Kupogoa na Kupunguza",
  "Garden area has been cleared": "Uchafu umetolewa",
  "Garden area has been watered": "Kumwagilia",
  "Safe paths have been created": "Njia Safi na zimechongwa",
  "Garden has been maintained with care": "Matengenezo ya zana za kazi.",
  "Branches have been cut": "Kupogoa na Kupunguza",
  "Damaged plants have been removed or replaced": "Majani yasiyotakiwa yameondolewa.",
  "Store door is locked and the key has been handed over": "Baada ya usofi vitendea kazi vyote vimesafishwa",
  "Store door is locked and the key has been returned to the store": "Baada ya usofi vitendea kazi vyote vimerudishwa store",
  "All equipment is returned to its place and organized": "Je wafanyakazi wanatumza vitendea kazi vilivyokabidhiwa",
  "Used equipment has been washed and returned to the store": "Baada ya usofi vitendea kazi vyote vimesafishwa",
  "Used equipment is returned to its proper location": "Baada ya usofi vitendea kazi vyote vimerudishwa store",
  "Equipment needing repair has been separated and reported": "Vitu vyote vinavyoharibika vinakaguliwa na kuhifadhiwa",
  "Worker can perform within the required time": "Je wanafika na kuondoka ndani ya wakati",
  "Worker is honest and hardworking": "Je wanaheshimiana na kushirikiana",
  "Worker completes tasks before the required time": "Wanatekeleza majukumu yao kwa ufanisi",
  "Worker is present in all assigned work areas": "Wanakuwepo maeneo yao ya kazi mda wote.",
  "Worker does not leave the work area without informing the supervisor": "Wanamuheshimu kiongozi wao anapowaambia jambo",
  "Worker follows instructions and performs assigned work": "Wanatoa taarifa mapema endapo kuna dharula",
};

const normalizedTranslations = Object.fromEntries(Object.entries(translations).map(([key, value]) => [key.trim().replace(/\s+/g, " "), value]));
const STORAGE_KEY = "whitebird-language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "sw";
    return window.localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "sw";
  });
  const setLanguage = (next: Language) => {
    setLanguageState(next);
    if (typeof window !== "undefined") window.localStorage.setItem(STORAGE_KEY, next);
  };
  const translate = (english: string) => {
    if (language !== "sw") return english;
    const normalized = english.trim().replace(/\s+/g, " ");
    const direct = translations[english] ?? normalizedTranslations[normalized];
    if (direct !== undefined) return direct;
    if (normalized.startsWith("Daily Cleanliness Survey · ")) return "TAARIFA YA USAFI · ENEO MAALUM";
    return english;
  };
  const value = useMemo<LanguageContextValue>(() => ({ language, setLanguage, toggleLanguage: () => setLanguage(language === "sw" ? "en" : "sw"), t: translate }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used within LanguageProvider");
  return value;
}
