import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Language = "sw" | "en";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (english: string) => string;
};

const translations: Record<string, string> = {
  "Today": "Leo",
  "System administrator": "Msimamizi wa mfumo",
  "Human resources": "Rasilimali watu",
  "Store manager": "Msimamizi wa stoo",
  "General supervisor": "Msimamizi mkuu",
  "Assistant general supervisor": "Msaidizi wa msimamizi mkuu",
  "Zone supervisor": "Msimamizi wa kanda",
  "Site manager / supervisor": "Msimamizi wa eneo",
  "Management viewer": "Mtazamaji wa usimamizi",
  "HR onboarding": "Usajili wa wafanyakazi",
  "People registry": "Orodha ya watu",
  "Daily cleanliness": "Usafi wa kila siku",
  "Stores & stock": "Stoo na vifaa",
  "Administration": "Usimamizi",
  "Users & roles": "Watumiaji na nafasi",
  "Sites, zones & GIS": "Maeneo, kanda na ramani",
  "Integration settings": "Mipangilio ya miunganisho",
  "Sites & zones": "Maeneo na kanda",
  "Assignments & shifts": "Ugawaji na zamu",
  "Trainee management": "Usimamizi wa wanafunzi",
  "Attendance": "Mahudhurio",
  "Inspections": "Ukaguzi",
  "Issues & jobs": "Matatizo na kazi",
  "Reports": "Ripoti",
  "Notifications": "Taarifa",
  "Account & security": "Akaunti na usalama",
  "Report archive": "Jalada la ripoti",
  "Operations": "Kazi za kila siku",
  "Workspace": "Eneo la kazi",
  "Your current scope": "Eneo lako la kazi",
  "Your accessible sites and actions are controlled by the White Bird policy layer.": "Maeneo na kazi unazoruhusiwa zinaongozwa na kanuni za White Bird.",
  "Refresh": "Sasisha",
  "Good day": "Habari",
  "Role command centre": "Kituo cha kazi",
  "Visible sites": "Maeneo yanayoonekana",
  "Active sites": "Maeneo yanayofanya kazi",
  "Open issues": "Matatizo yaliyo wazi",
  "Overdue jobs": "Kazi zilizochelewa",
  "Low-stock items": "Vifaa vilivyopungua",
  "Attendance rate": "Asilimia ya mahudhurio",
  "Reports awaiting action": "Ripoti zinazosubiri hatua",
  "Cleaners": "Wasafi",
  "Live from your permitted operational scope": "Taarifa za moja kwa moja kutoka eneo lako la kazi",
  "Building your operational picture": "Tunatayarisha muhtasari wa kazi zako",
  "Your metrics will appear here": "Vipimo vyako vitaonekana hapa",
  "Signals needing attention": "Taarifa zinazohitaji uangalifu",
  "View all": "Ona zote",
  "No unread operational signals are available.": "Hakuna taarifa mpya za kazi kwa sasa.",
  "Work in motion": "Kazi zinazoendelea",
  "Choose the next responsible action.": "Chagua hatua inayofuata ya kufanya.",
  "Role-aware": "Kulingana na nafasi yako",
  "Reporting chain": "Mfuatano wa ripoti",
  "Keep the handover moving.": "Endeleza makabidhiano ya kazi.",
  "Open reporting workspace": "Fungua eneo la ripoti",
  "Daily cleanliness declaration": "Taarifa ya usafi wa kila siku",
  "Complete today’s site sheet, one clear row at a time.": "Jaza fomu ya leo, mstari mmoja kwa wakati.",
  "Assigned site": "Eneo ulilopangiwa",
  "Date": "Tarehe",
  "daily declaration": "taarifa ya kila siku",
  "Daily worksheet progress": "Maendeleo ya fomu ya leo",
  "questions answered": "maswali yamejibiwa",
  "areas submitted": "maeneo yamewasilishwa",
  "Open today’s sheet": "Fungua fomu ya leo",
  "Saved answers stay auditable.": "Majibu yaliyohifadhiwa yanaonekana kwenye kumbukumbu ya ukaguzi.",
  "This answer was already saved. The worksheet is now synchronized with the server record.": "Jibu hili lilikuwa tayari limehifadhiwa. Fomu sasa imesawazishwa na rekodi ya seva.",
  "declaration submitted for review.": "imetumwa kwa ukaguzi.",
  "What happened and what must happen next?": "Nini kimetokea na hatua gani ifuatayo inahitajika?",
  "Area": "Eneo",
  "Operational area": "Eneo la kazi",
  "Select assigned site": "Chagua eneo ulilopangiwa",
  "Once the dashboard service is connected and returns data for your role, White Bird will show only the KPIs you are permitted to see.": "Huduma ya dashibodi ikiunganishwa, White Bird itaonyesha vipimo unavyoruhusiwa kuona.",
  "How to use this sheet:": "Jinsi ya kutumia fomu hii:",
  "Done on time": "Imekamilika kwa wakati",
  "Exception": "Tatizo / haijakamilika",
  "Save": "Hifadhi",
  "Yes": "Ndiyo",
  "No": "Hapana",
  "Evidence / responsible cleaner": "Maelezo / msafi anayehusika",
  "Question / check": "Swali / ukaguzi",
  "No exception note required.": "Hakuna maelezo ya tatizo yanayohitajika.",
  "Select responsible cleaner": "Chagua msafi anayehusika",
  "Saved": "Imehifadhiwa",
  "Save answer": "Hifadhi jibu",
  "Save exception": "Hifadhi tatizo",
  "Submit area": "Wasilisha eneo",
  "Open area": "Fungua eneo",
  "Refresh sheet": "Sasisha fomu",
  "No daily cleanliness templates configured": "Hakuna fomu za usafi zilizowekwa",
  "Choose Done on time or Exception before saving.": "Chagua Imekamilika au Tatizo kabla ya kuhifadhi.",
  "Add a corrective note for this exception.": "Andika hatua ya kurekebisha tatizo hili.",
  "Loading today’s questions and assigned cleaners": "Tunapakia maswali ya leo na wasafi waliopangiwa",
  "Loading assigned cleanliness scope": "Tunapakia eneo lako la usafi",
  "Open this area to load its daily questions into the worksheet.": "Fungua eneo hili ili kupakia maswali yake ya leo.",
  "English": "Kiingereza",
  "Kiswahili": "Kiswahili",
  "Language": "Lugha",
  "Quick action": "Hatua ya haraka",
  "Fast track": "Njia ya haraka",
  "Start an authorised task": "Anza kazi iliyoruhusiwa",
  "Record today’s attendance": "Weka mahudhurio ya leo",
  "Complete daily cleanliness": "Jaza usafi wa leo",
  "Raise an issue or job": "Wasilisha tatizo au kazi",
  "Start an inspection": "Anza ukaguzi",
  "Onboard cleaners": "Sajili wasafi",
  "Trainee qualification": "Uthibitisho wa mwanafunzi",
  "HR reporting": "Ripoti za HR",
  "Requests to fulfill": "Maombi ya kutimiza",
  "Supply reporting": "Ripoti za vifaa",
  "Governance evidence": "Ushahidi wa usimamizi",
  "Stock control": "Udhibiti wa vifaa",
  "The workday starts with the right stock in the right place.": "Siku ya kazi huanza vifaa sahihi vikiwa mahali sahihi.",
  "Configure the platform so every team can execute clearly.": "Weka mfumo ili kila timu ifanye kazi kwa uwazi.",
  "People move forward when every gate is visible.": "Wafanyakazi huendelea vizuri kila hatua inapoonekana.",
  "Own the cleaner lifecycle, trainee evidence, and workforce assignment integrity.": "Simamia safari ya msafi, ushahidi wa mwanafunzi, na ugawaji sahihi wa wafanyakazi.",
  "Own the configured stock chain from count to fulfillment and movement evidence.": "Simamia vifaa kutoka kuhesabu hadi kutimiza mahitaji na kumbukumbu za matumizi.",
  "Keep users, sites, zones, shifts, and permissions governed from one administration boundary.": "Simamia watumiaji, maeneo, kanda, zamu, na ruhusa kutoka sehemu moja.",
  "Your workspace brings together the most important operational signals for the scope you are trusted to manage.": "Eneo lako la kazi linaonyesha taarifa muhimu za maeneo unayoruhusiwa kusimamia.",
  "Register individuals or preview a validated HR workbook.": "Sajili mtu au kagua faili la HR lililothibitishwa.",
  "Review evaluations, due dates, and final evidence.": "Kagua tathmini, tarehe muhimu, na ushahidi wa mwisho.",
  "Maintain workforce placement and shift integrity.": "Dumisha ugawaji wa wafanyakazi na usahihi wa zamu.",
  "Review workforce handover and documentation gaps.": "Kagua makabidhiano ya wafanyakazi na mapungufu ya nyaraka.",
  "Process configured inventory and supply risks.": "Shughulikia vifaa vilivyowekwa na hatari za upungufu.",
  "Review site needs and keep quantities accountable.": "Kagua mahitaji ya eneo na linda usahihi wa idadi.",
  "Track stock movements, requests, and exceptions.": "Fuatilia matumizi ya vifaa, maombi, na matatizo.",
  "Configure users, roles, sites, zones, and shifts.": "Weka watumiaji, nafasi, maeneo, kanda, na zamu.",
  "Maintain the operating estate and zone relationships.": "Dumisha maeneo ya kazi na uhusiano wa kanda.",
  "Review audit and reporting health.": "Kagua afya ya kumbukumbu na ripoti.",
  "Record, submit, or review today’s site attendance.": "Weka, wasilisha, au kagua mahudhurio ya leo.",
  "Complete evidence-led field checks and reviews.": "Kamilisha ukaguzi wa maeneo kwa ushahidi.",
  "Move priority work through verification and closure.": "Pelega kazi muhimu hadi kuthibitishwa na kufungwa.",
  "Review low-stock signals and supply requests.": "Kagua ishara za upungufu na maombi ya vifaa.",
  "Site reports, zone summaries, and management visibility follow a deliberate reviewed sequence.": "Ripoti za maeneo na muhtasari wa kanda hupitia hatua ya ukaguzi iliyo wazi.",
  "No reporting status is currently available for this scope.": "Hakuna hali ya ripoti inayopatikana kwa eneo hili kwa sasa.",
  "Operational signal layers": "Tabaka za taarifa za kazi",
  "Trend endpoints, ready for your scope.": "Mwelekeo wa kazi kwa eneo lako.",
  "Attendance trend": "Mwelekeo wa mahudhurio",
  "Issue categories": "Aina za matatizo",
  "Inspection quality": "Ubora wa ukaguzi",
  "Live data appears when its dashboard endpoint is connected.": "Taarifa halisi zitaonekana huduma ya dashibodi ikiunganishwa.",
  "Charts respect both role permissions and the visible site scope supplied by White Bird.": "Michoro inaheshimu nafasi yako na maeneo yanayoonekana kwenye White Bird.",
  "Source data only · no fabricated results": "Taarifa halisi tu · hakuna matokeo ya kutengenezwa",
  "Lobby": "Ukumbi",
  "Rooms": "Vyumba",
  "Pool Deck": "Eneo la bwawa",
  "Toilet facilities": "Huduma za vyoo",
  "Garden and grounds": "Bustani na mazingira ya nje",
  "Reception and entrance": "Mapokezi na mlango wa kuingia",
  "Shared and public areas": "Maeneo ya pamoja na ya umma",
  "Daily Cleanliness Survey": "Uchunguzi wa Usafi wa Kila Siku",
  "Daily Cleanliness Survey · Rooms": "Uchunguzi wa Usafi wa Kila Siku · Vyumba",
  "Daily Cleanliness Survey · Pool Deck": "Uchunguzi wa Usafi wa Kila Siku · Eneo la bwawa",
  "Daily Cleanliness Survey · Toilet facilities": "Uchunguzi wa Usafi wa Kila Siku · Huduma za vyoo",
  "Daily Cleanliness Survey · Garden and grounds": "Uchunguzi wa Usafi wa Kila Siku · Bustani na mazingira ya nje",
  "Daily Cleanliness Survey · Reception and entrance": "Uchunguzi wa Usafi wa Kila Siku · Mapokezi na mlango wa kuingia",
  "Daily Cleanliness Survey · Shared and public areas": "Uchunguzi wa Usafi wa Kila Siku · Maeneo ya pamoja na ya umma",
  "Daily Cleanliness Survey · Lobby": "Uchunguzi wa Usafi wa Kila Siku · Ukumbi",
  "Ready-made daily cleanliness survey for operational site review.": "Uchunguzi wa usafi wa kila siku uliotayarishwa kwa ukaguzi wa eneo la kazi.",
  "Area cleaned to the agreed schedule": "Eneo limesafishwa kwa ratiba iliyokubaliwa",
  "Was the area completed within the required service window?": "Je, eneo limekamilishwa ndani ya muda uliopangwa wa huduma?",
  "High-touch surfaces cleaned": "Sehemu zinazoguswa mara kwa mara zimesafishwa",
  "Check doors, handles, switches, rails, and other high-touch surfaces.": "Kagua milango, vishikio, swichi, reli, na sehemu nyingine zinazoguswa mara kwa mara.",
  "Waste removed and bins reset": "Taka zimeondolewa na mapipa yamepangwa upya",
  "Confirm waste has been removed and bins are clean and correctly lined.": "Thibitisha taka zimeondolewa na mapipa ni safi na yana mifuko vizuri.",
  "Consumables and hygiene supplies available": "Vifaa vya matumizi na usafi vinapatikana",
  "Check soap, tissue, paper products, and other configured consumables.": "Kagua sabuni, tissue, karatasi, na vifaa vingine vilivyowekwa.",
  "Exception details and corrective action": "Maelezo ya tatizo na hatua ya kurekebisha",
  "Text answer": "Jibu la maandishi",
  "Write your answer": "Andika jibu lako",
  "Write an answer before saving.": "Andika jibu kabla ya kuhifadhi.",
  "If any item failed, record who is responsible, what was done, and the next review time.": "Kama kuna jambo halijakamilika, andika anayehusika, kilichofanyika, na muda wa ukaguzi unaofuata.",
  "Toilets / Vyooni": "Vyoo",
  "Offices / Ofisini": "Ofisi",
  "Indoor areas / Eneo la ndani": "Maeneo ya ndani",
  "Outdoor areas / Eneo la nje": "Maeneo ya nje",
  "Garden / Bustani": "Bustani",
  "Store and equipment / Usimamizi wa store": "Stoo na vifaa",
  "Staff performance / Maendeleo ya wafanyakazi": "Utendaji wa wafanyakazi",
  "Floor and wall surfaces have been washed and cleaned": "Sakafu na kuta zimeoshwa na kusafishwa",
  "Mirrors have been cleaned": "Vioo vimesafishwa",
  "Rubbish bin has been cleaned": "Pipa la taka limesafishwa",
  "Toilet has been washed and cleaned": "Choo kimeoshwa na kusafishwa",
  "Soap, brushes, and cleaning tools are washed and stored properly": "Sabuni, brashi na vifaa vya usafi vimeoshwa na kuwekwa vizuri",
  "Water has been put into the cleaning tank": "Maji yamewekwa kwenye tanki la usafi",
  "Water has been put into the hand-washing container": "Maji yamewekwa kwenye chombo cha kunawa mikono",
  "Towels have been placed": "Taulo zimewekwa",
  "Toilet paper has been placed": "Karatasi ya choo imewekwa",
  "Floor and wall surfaces have been cleaned": "Sakafu na kuta zimesafishwa",
  "Chairs, tables, and office equipment have been dusted": "Viti, meza na vifaa vya ofisi vimeondolewa vumbi",
  "Rubbish bin has been washed and cleaned": "Pipa la taka limeoshwa na kusafishwa",
  "Desk has been arranged and cleaned": "Meza imepangwa na kusafishwa",
  "Floors, doors, and windows have been cleaned": "Sakafu, milango na madirisha vimesafishwa",
  "Floors and doors have been cleaned": "Sakafu na milango vimesafishwa",
  "Tables have been arranged and curtains straightened": "Meza zimepangwa na mapazia yamenyooshwa",
  "Ceiling has been wiped and cobwebs removed": "Dari limefutwa na utando wa buibui umeondolewa",
  "Furniture has been arranged": "Samani zimepangwa",
  "Rubbish bin has been placed": "Pipa la taka limewekwa mahali pake",
  "Stairs have been cleaned before opening": "Ngazi zimesafishwa kabla ya kufungua",
  "Entrance has been wiped and cleaned": "Sehemu ya kuingilia imefutwa na kusafishwa",
  "Furniture has been arranged and curtains straightened": "Samani zimepangwa na mapazia yamenyooshwa",
  "Bin has been placed": "Pipa limewekwa mahali pake",
  "Water has been put in the water container and it has been covered": "Maji yamewekwa kwenye chombo na kimefunikwa",
  "Grass has been cut": "Nyasi zimekatwa",
  "Parking area has been cleaned": "Eneo la maegesho limesafishwa",
  "Fence has been cleaned": "Uzio umesafishwa",
  "Paths and passages have been cleaned": "Njia na mapito zimesafishwa",
  "All surrounding areas have been cleaned": "Maeneo yote yanayozunguka yamesafishwa",
  "Outdoor area has been watered": "Eneo la nje limemwagiliwa maji",
  "Rubbish bin has been wiped and cleaned": "Pipa la taka limefutwa na kusafishwa",
  "Flower beds have been watered": "Maua yamepata maji",
  "Flowers have been pruned": "Maua yamepunguzwa matawi",
  "Garden area has been cleared": "Eneo la bustani limeondolewa taka",
  "Garden area has been watered": "Eneo la bustani limemwagiliwa maji",
  "Safe paths have been created": "Njia salama zimetengenezwa",
  "Garden has been maintained with care": "Bustani imetunzwa vizuri",
  "Branches have been cut": "Matawi yamekatwa",
  "Damaged plants have been removed or replaced": "Mimea iliyoharibika imeondolewa au kubadilishwa",
  "Store door is locked and the key has been handed over": "Mlango wa stoo umefungwa na ufunguo umekabidhiwa",
  "Store door is locked and the key has been returned to the store": "Mlango wa stoo umefungwa na ufunguo umerudishwa stoo",
  "All equipment is returned to its place and organized": "Vifaa vyote vimerudishwa na kupangwa mahali pake",
  "Used equipment has been washed and returned to the store": "Vifaa vilivyotumika vimeoshwa na kurudishwa stoo",
  "Used equipment is returned to its proper location": "Vifaa vilivyotumika vimerudishwa mahali pake",
  "Equipment needing repair has been separated and reported": "Vifaa vinavyohitaji matengenezo vimetengwa na kuripotiwa",
  "Worker can perform within the required time": "Mfanyakazi anaweza kumaliza kazi kwa wakati unaotakiwa",
  "Worker is honest and hardworking": "Mfanyakazi ni mwaminifu na mchapakazi",
  "Worker completes tasks before the required time": "Mfanyakazi anakamilisha kazi kabla ya muda unaotakiwa",
  "Worker is present in all assigned work areas": "Mfanyakazi yupo katika maeneo yote aliyopangiwa",
  "Worker does not leave the work area without informing the supervisor": "Mfanyakazi haondoki eneo la kazi bila kumjulisha msimamizi",
  "Worker follows instructions and performs assigned work": "Mfanyakazi anafuata maelekezo na kufanya kazi aliyopewa",
};

const normalizedTranslations = Object.fromEntries(Object.entries(translations).map(([key, value]) => [key.trim().replace(/\s+/g, " "), value]));
const STORAGE_KEY = "whitebird-language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "sw";
    return window.localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "sw";
  });
  const setLanguage = (next: Language) => {
    setLanguageState(next);
    if (typeof window !== "undefined") window.localStorage.setItem(STORAGE_KEY, next);
  };
  const value = useMemo<LanguageContextValue>(() => ({ language, setLanguage, toggleLanguage: () => setLanguage(language === "sw" ? "en" : "sw"), t: (english) => language === "sw" ? (translations[english] || normalizedTranslations[english.trim().replace(/\s+/g, " ")] || english) : english }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used within LanguageProvider");
  return value;
}
