# Generated by Django 5.2.17 on 2026-08-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models
import apps.accounts.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={"unique": "A user with that email already exists."},
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tanzanian or international E.164 format, e.g. +2557xx xxx xxx.",
                        max_length=16,
                        validators=[apps.accounts.validators.validate_phone],
                    ),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=150)),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system_admin", "System Admin"),
                            ("site_supervisor", "Site Supervisor"),
                            ("zone_supervisor", "Zone Supervisor"),
                            ("assistant_general_supervisor", "Assistant General Supervisor"),
                            ("general_supervisor", "General Supervisor"),
                            ("management_viewer", "Management Viewer"),
                        ],
                        default="management_viewer",
                        max_length=40,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Dar_es_Salaam",
                        help_text="IANA timezone used for date rendering and notifications.",
                        max_length=64,
                        validators=[apps.accounts.validators.validate_timezone],
                    ),
                ),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/%Y/%m/")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive accounts cannot log in and are excluded from operations."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Designates whether the user can log into the Django admin."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
                "permissions": [
                    ("submit_site_report", "Can submit site reports"),
                    ("review_zone_report", "Can review zone reports"),
                    ("review_assistant_report", "Can review assistant general supervisor reports"),
                    ("approve_general_report", "Can approve general supervisor reports"),
                    ("assign_job", "Can assign jobs"),
                    ("verify_job", "Can verify completed jobs"),
                    ("approve_trainee", "Can approve trainees"),
                    ("manage_site_configuration", "Can manage site configuration"),
                    ("view_sensitive_cleaner_documents", "Can view sensitive cleaner documents"),
                    ("export_site_management_data", "Can export site management data"),
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=64)),
                ("key", models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API token",
                "verbose_name_plural": "API tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
