# Generated by Django 5.2.17 on 2026-08-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('submit_site_report', 'Can submit site reports'), ('review_zone_report', 'Can review zone reports'), ('review_assistant_report', 'Can review assistant general supervisor reports'), ('approve_general_report', 'Can approve general supervisor reports'), ('assign_job', 'Can assign jobs'), ('verify_job', 'Can verify completed jobs'), ('approve_trainee', 'Can approve trainees'), ('manage_site_configuration', 'Can manage site configuration'), ('manage_cleaners', 'Can register and onboard cleaners'), ('view_sensitive_cleaner_documents', 'Can view sensitive cleaner documents'), ('export_site_management_data', 'Can export site management data')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
