# Generated by Django 5.2.17 on 2026-08-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("submit_site_report", "Can submit site reports"),
                    ("review_zone_report", "Can review zone reports"),
                    ("review_assistant_report", "Can review assistant general supervisor reports"),
                    ("approve_general_report", "Can approve general supervisor reports"),
                    ("assign_job", "Can assign jobs"),
                    ("verify_job", "Can verify completed jobs"),
                    ("approve_trainee", "Can approve trainees"),
                    ("manage_site_configuration", "Can manage site configuration"),
                    ("manage_cleaners", "Can register and onboard cleaners"),
                    ("import_cleaners", "Can import cleaners from a validated workbook"),
                    ("manage_cleaner_assignments", "Can assign cleaners and trainees to sites and shifts"),
                    ("manage_trainee_lifecycle", "Can evaluate and qualify trainees"),
                    ("manage_store_inventory", "Can manage stock catalogs, counts, requests, and fulfillment"),
                    ("view_sensitive_cleaner_documents", "Can view sensitive cleaner documents"),
                    ("export_site_management_data", "Can export site management data"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "System Admin"),
                    ("hr", "Human Resources"),
                    ("store_manager", "Store Manager"),
                    ("site_supervisor", "Site Supervisor"),
                    ("zone_supervisor", "Zone Supervisor"),
                    ("assistant_general_supervisor", "Assistant General Supervisor"),
                    ("general_supervisor", "General Supervisor"),
                    ("management_viewer", "Management Viewer"),
                ],
                default="management_viewer",
                max_length=40,
            ),
        ),
    ]
