/** Coastal Ledger workflow composer: backend-aligned, role-aware forms with safe scope selections. */
import { FormEvent, useEffect, useState } from "react";
import { Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { api, asPaginated, readableApiError } from "@/lib/api";
import { formatDisplayValue } from "@/components/WorkspacePrimitives";
import { useAuth } from "@/contexts/AuthContext";

export type ActionKind = "issue" | "cleaner" | "inspection" | "stock_request" | "general_report";
const copy: Record<ActionKind, { label: string; title: string; description: string }> = {
  issue: { label: "Raise issue", title: "Raise a site issue", description: "Create an operational issue for a permitted site. Prioritise clarity so the next reviewer can act without delay." },
  cleaner: { label: "Register cleaner", title: "Register a cleaner", description: "Complete the first step of cleaner onboarding. Identity documents and verification remain a separate controlled review." },
  inspection: { label: "Start inspection", title: "Start a field inspection", description: "Open a draft inspection against a permitted site, area, and active inspection template." },
  stock_request: { label: "Request stock", title: "Request configured stock", description: "Select a configured store item, report what remains, and explain the quantity requested. Site supervisors never need to type internal IDs." },
  general_report: { label: "Generate management report", title: "Generate a management report", description: "Generate the general report for a selected reporting date. The reporting chain remains permission-controlled." },
};

function isCleanerManager(role?: string, permissions?: Record<string, unknown> | null) {
  if (role === "system_admin") return true;
  if (!permissions) return false;
  return permissions["accounts.manage_cleaners"] === true || JSON.stringify(permissions).toLowerCase().includes("manage_cleaners");
}

export function ActionComposer({ kind, onComplete }: { kind: ActionKind; onComplete?: () => void }) {
  const { user, permissions } = useAuth();
  const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const config = copy[kind];
  if (kind === "cleaner" && !isCleanerManager(user?.role, permissions)) return null;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const fields = new FormData(event.currentTarget); const value = (name: string) => String(fields.get(name) || "").trim(); const number = (name: string) => Number(value(name)); let endpoint = ""; let payload: Record<string, unknown> = {};
    if (kind === "issue") { endpoint = "/issues"; payload = { title: value("title"), description: value("description"), site_id: number("site_id"), priority: value("priority"), issue_category: value("issue_category"), source: "manual" }; }
    if (kind === "cleaner") { endpoint = "/cleaners"; payload = { first_name: value("first_name"), last_name: value("last_name"), id_type: value("id_type"), id_number: value("id_number"), birth_date: value("birth_date"), gender: value("gender"), living_location: value("living_location"), phone_number: value("phone_number"), near_person_name: value("near_person_name"), near_person_relationship: value("near_person_relationship"), near_person_phone: value("near_person_phone"), notes: value("notes") }; }
    if (kind === "inspection") { endpoint = "/inspections"; payload = { site_id: number("site_id"), area_id: number("area_id"), template_id: number("template_id"), inspection_date: value("inspection_date") || undefined, shift_id: value("shift_id") ? number("shift_id") : undefined, notes: value("notes") }; }
    if (kind === "stock_request") { endpoint = `/stores/${number("store_id")}/requests`; payload = { request_date: value("request_date") || undefined, notes: value("notes"), items: [{ store_item_id: number("store_item_id"), requested_quantity: number("requested_quantity"), notes: value("item_notes"), quantity_left: number("quantity_left") }] }; }
    if (kind === "general_report") { endpoint = "/reports/general/generate"; payload = { report_date: value("report_date") }; }
    setSubmitting(true); setError(null);
    try { await api.post(endpoint, payload); setOpen(false); onComplete?.(); } catch (caught) { setError(readableApiError(caught).message); } finally { setSubmitting(false); }
  }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-[#0F7667] text-white hover:bg-[#0B6155]"><Plus size={16} /> {config.label}</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto border-[#DDD5C7] bg-[#FFFDF8] sm:max-w-lg"><DialogHeader><p className="ledger-label text-[#0F7667]">Authorised action</p><DialogTitle className="font-serif text-3xl text-[#193D41]">{config.title}</DialogTitle><DialogDescription className="leading-6 text-[#61706B]">{config.description}</DialogDescription></DialogHeader><form className="mt-3 space-y-4" onSubmit={submit}>{kind === "cleaner" && <CleanerFields />}{kind === "issue" && <IssueFields />}{kind === "inspection" && <InspectionFields />}{kind === "stock_request" && <StockRequestFields open={open} />}{kind === "general_report" && <Field label="Report date" name="report_date" type="date" required />}{error && <p className="rounded-lg bg-[#FBE4DD] px-3 py-2 text-sm text-[#9D3D28]">{error}</p>}<div className="flex justify-end gap-2 pt-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={submitting} className="bg-[#0F7667] text-white hover:bg-[#0B6155]">{submitting && <Loader2 className="animate-spin" size={16} />} Submit action</Button></div></form></DialogContent></Dialog>;
}

function CleanerFields() { return <><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" name="first_name" required /><Field label="Last name" name="last_name" required /></div><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Identity type" name="id_type" values={["birth_certificate", "nida", "zanzibar_id"]} /><Field label="Identity number" name="id_number" required /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Birth date" name="birth_date" type="date" required /><SelectField label="Gender" name="gender" values={["unspecified", "female", "male", "other"]} /></div><Field label="Phone number" name="phone_number" /><Field label="Living location" name="living_location" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Emergency contact" name="near_person_name" /><Field label="Relationship" name="near_person_relationship" /></div><Field label="Emergency phone" name="near_person_phone" /><TextAreaField label="Onboarding notes" name="notes" /></>; }
function IssueFields() { return <><Field label="Issue title" name="title" required /><div className="grid gap-4 sm:grid-cols-2"><Field label="Site ID" name="site_id" type="number" required /><SelectField label="Priority" name="priority" values={["low", "medium", "high", "urgent"]} /></div><SelectField label="Category" name="issue_category" values={["maintenance", "cleaning", "safety", "security", "stock", "other"]} /><TextAreaField label="Context" name="description" /></>; }
function InspectionFields() { return <><div className="grid gap-4 sm:grid-cols-2"><Field label="Site ID" name="site_id" type="number" required /><Field label="Area ID" name="area_id" type="number" required /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Template ID" name="template_id" type="number" required /><Field label="Inspection date" name="inspection_date" type="date" /></div><Field label="Shift ID (if applicable)" name="shift_id" type="number" /><TextAreaField label="Inspection notes" name="notes" /></>; }
function StockRequestFields({ open }: { open: boolean }) { const [stores, setStores] = useState<Record<string, unknown>[]>([]); const [items, setItems] = useState<Record<string, unknown>[]>([]); const [storeId, setStoreId] = useState(""); useEffect(() => { if (open) void api.get("/stores?page_size=100").then((response) => setStores(asPaginated(response).results)); }, [open]); useEffect(() => { if (!storeId) { setItems([]); return; } void api.get(`/stores/${storeId}/items`).then((response) => setItems(Array.isArray(response) ? response : asPaginated(response).results)); }, [storeId]); return <><div className="grid gap-2"><Label htmlFor="store_id">Assigned store</Label><select id="store_id" name="store_id" required value={storeId} onChange={(event) => setStoreId(event.target.value)} className="h-10 rounded-md border border-[#D8D2C5] bg-white px-3 text-sm"><option value="">Select configured store</option>{stores.map((store) => <option key={String(store.id)} value={String(store.id)}>{formatDisplayValue(store.name || store.store_name, `Store ${formatDisplayValue(store.id)}`)}</option>)}</select></div><div className="grid gap-2"><Label htmlFor="store_item_id">Stock item</Label><select id="store_item_id" name="store_item_id" required disabled={!storeId} className="h-10 rounded-md border border-[#D8D2C5] bg-white px-3 text-sm"><option value="">Select configured item</option>{items.map((item) => <option key={String(item.id)} value={String(item.id)}>{formatDisplayValue(item.item_name || item.name || item.item_code, `Item ${formatDisplayValue(item.id)}`)}</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Quantity left" name="quantity_left" type="number" required /><Field label="Quantity requested" name="requested_quantity" type="number" required /></div><Field label="Request date" name="request_date" type="date" /><TextAreaField label="Reason or message" name="notes" /><TextAreaField label="Item notes" name="item_notes" /></>; }
function Field({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <div className="grid gap-2"><Label htmlFor={name}>{label}{required && <span className="ml-1 text-[#B54B2E">*</span>}</Label><Input id={name} name={name} type={type} required={required} min={type === "number" ? "0" : undefined} className="border-[#D8D2C5] bg-white" /></div>; }
function TextAreaField({ label, name }: { label: string; name: string }) { return <div className="grid gap-2"><Label htmlFor={name}>{label}</Label><Textarea id={name} name={name} className="min-h-20 border-[#D8D2C5] bg-white" /></div>; }
function SelectField({ label, name, values }: { label: string; name: string; values: string[] }) { return <div className="grid gap-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} defaultValue={values[0]} className="h-10 rounded-md border border-[#D8D2C5] bg-white px-3 text-sm">{values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></div>; }
