# Generated by Django 5.2.17 on 2026-08-13 18:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("archive", "Archive"),
                            ("restore", "Restore"),
                            ("status_change", "Status Change"),
                            ("assign", "Assign"),
                            ("unassign", "Unassign"),
                            ("login", "Login"),
                            ("token_create", "Token Create"),
                            ("token_revoke", "Token Revoke"),
                            ("file_download", "File Download"),
                            ("event_published", "Event Published"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=96)),
                ("object_id", models.CharField(db_index=True, max_length=36)),
                ("object_repr", models.CharField(blank=True, default="", max_length=255)),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action; null for system actors.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log",
                "verbose_name_plural": "Audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["model_name", "object_id"], name="core_auditl_model_n_3fb686_idx"),
                    models.Index(fields=["user", "created_at"], name="core_auditl_user_id_413764_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("aggregate_type", models.CharField(db_index=True, max_length=128)),
                ("aggregate_id", models.CharField(db_index=True, max_length=36)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("published", "Published"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain event",
                "verbose_name_plural": "Domain events",
                "ordering": ["-occurred_at"],
                "indexes": [models.Index(fields=["status", "occurred_at"], name="core_domain_status_b078d0_idx")],
            },
        ),
    ]
