import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Building2, ClipboardCheck, ClipboardList, FileBarChart2, HardHat, PackageSearch, RefreshCw, Settings2, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/AppShell";
import { OperationalCalendar } from "@/components/OperationalCalendar";
import { ApiErrorPanel, EmptyPanel, LoadingPanel, StatusBadge, WorkspaceHeader, formatDisplayValue } from "@/components/WorkspacePrimitives";
import { api } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { roleLabels } from "@/lib/navigation";
import { useLanguage } from "@/contexts/LanguageContext";

interface DashboardData { stats: Record<string, unknown>; kpis: Record<string, unknown>; notifications: Record<string, unknown>[]; reports: Record<string, unknown>; }
const metricLabels: Record<string, string> = { total_sites: "Visible sites", active_sites: "Active sites", open_issues: "Open issues", overdue_jobs: "Overdue jobs", low_stock_items: "Low-stock items", attendance_rate: "Attendance rate", pending_reports: "Reports awaiting action", total_cleaners: "Cleaners" };
const metricsFrom = (data: Record<string, unknown>) => Object.entries(data).filter(([, value]) => typeof value === "number" || typeof value === "string").slice(0, 6).map(([key, value]) => ({ label: metricLabels[key] || key.replaceAll("_", " "), value: typeof value === "number" && key.includes("rate") ? `${value}%` : String(value) }));

export default function DashboardPage() {
  const { user } = useAuth(); const { t } = useLanguage();
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    const responses = await Promise.allSettled([api.get<Record<string, unknown>>("/auth/me/stats"), api.get<Record<string, unknown>>("/dashboards/kpis"), api.get<Record<string, unknown>[]>("/notifications"), api.get<Record<string, unknown>>("/reports/status")]);
    const failed = responses.find((response) => response.status === "rejected");
    if (failed?.status === "rejected") { setError(failed.reason); setLoading(false); return; }
    const [stats, kpis, notifications, reports] = responses;
    setData({ stats: stats.status === "fulfilled" ? stats.value : {}, kpis: kpis.status === "fulfilled" ? kpis.value : {}, notifications: notifications.status === "fulfilled" ? notifications.value : [], reports: reports.status === "fulfilled" ? reports.value : {} }); setLoading(false);
  }, []);
  useEffect(() => { void load(); }, [load]);
  const metrics = useMemo(() => metricsFrom({ ...(data?.kpis || {}), ...(data?.stats || {}) }), [data]);
  const role = user?.role || "management_viewer";
  const actions = role === "hr" ? [{ href: "/hr/onboarding", icon: UsersRound, label: "Onboard cleaners", description: "Register individuals or preview a validated HR workbook." }, { href: "/trainees", icon: ShieldCheck, label: "Trainee qualification", description: "Review evaluations, due dates, and final evidence." }, { href: "/hr/assignments", icon: ClipboardList, label: "Assignments & shifts", description: "Maintain workforce placement and shift integrity." }, { href: "/reports", icon: FileBarChart2, label: "HR reporting", description: "Review workforce handover and documentation gaps." }] : role === "store_manager" ? [{ href: "/store-control", icon: PackageSearch, label: "Store control", description: "Process configured inventory and supply risks." }, { href: "/stores", icon: ClipboardList, label: "Requests to fulfill", description: "Review site needs and keep quantities accountable." }, { href: "/reports", icon: FileBarChart2, label: "Supply reporting", description: "Track stock movements, requests, and exceptions." }] : role === "system_admin" ? [{ href: "/admin", icon: Settings2, label: "Administration", description: "Configure users, roles, sites, zones, and shifts." }, { href: "/sites", icon: Building2, label: "Sites & zones", description: "Maintain the operating estate and zone relationships." }, { href: "/reports", icon: FileBarChart2, label: "Governance evidence", description: "Review audit and reporting health." }] : [{ href: "/attendance", icon: ClipboardCheck, label: "Attendance", description: "Record, submit, or review today’s site attendance." }, { href: "/inspections", icon: ShieldCheck, label: "Inspections", description: "Complete evidence-led field checks and reviews." }, { href: "/operations/issues", icon: HardHat, label: "Issues & jobs", description: "Move priority work through verification and closure." }, { href: "/stores", icon: PackageSearch, label: "Stock control", description: "Review low-stock signals and supply requests." }];

  return <AppShell><WorkspaceHeader eyebrow={t(roleLabels[role] || "Role command centre")} title={role === "system_admin" ? t("Configure the platform so every team can execute clearly.") : `${t("Good day")}${user?.first_name ? `, ${user.first_name}` : ""}.`} description={t("Your workspace brings together the most important operational signals for the scope you are trusted to manage.")} actions={<Button variant="outline" className="bg-[#FFFDF8]" onClick={() => void load()}><RefreshCw size={16} /> {t("Refresh")}</Button>} />
    {loading ? <LoadingPanel label={t("Building your operational picture")} /> : error ? <ApiErrorPanel error={error} onRetry={() => void load()} /> : <div className="space-y-7">
      {metrics.length ? <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{metrics.map((metric, index) => <div key={metric.label} className="relative overflow-hidden rounded-2xl border border-[#DDD7CA] bg-[#FFFDF8] p-5 shadow-[0_10px_28px_rgba(26,58,55,.04)] transition-transform duration-200 hover:-translate-y-0.5"><div className="absolute right-0 top-0 h-1 w-16 bg-[#D86143]" style={{ opacity: 1 - index * .12 }} /><p className="ledger-label text-[#687874]">{t(metric.label)}</p><p className="mt-3 font-serif text-4xl tracking-[-.04em] text-[#173B3E]">{metric.value}</p><p className="mt-2 text-xs text-[#70817C]">{t("Live from your permitted operational scope")}</p></div>)}</section> : <EmptyPanel title={t("Your metrics will appear here")} description={t("Once the dashboard service returns data for your role, White Bird will show only the KPIs you are permitted to see.")} />}
      <OperationalCalendar />
      <section className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><div className="rounded-2xl border border-[#DDD7CA] bg-[#FFFDF8] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="ledger-label text-[#0F7667]">{t("Work in motion")}</p><h3 className="mt-1 font-serif text-2xl text-[#1C4043]">{t("Choose the next responsible action.")}</h3></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{actions.map((action) => { const Icon = action.icon; return <Link href={action.href} key={action.href} className="group rounded-xl border border-[#E3DDD2] bg-[#FEFCF7] p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-[#D7A191] hover:shadow-[0_12px_26px_rgba(216,97,67,.10)]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#FBE9E3] text-[#C45232]"><Icon size={18} /></span><p className="mt-4 flex items-center justify-between font-bold text-[#21464A]">{t(action.label)}<ArrowRight size={16} className="text-[#C98772] transition-transform group-hover:translate-x-1" /></p><p className="mt-1 text-xs leading-5 text-[#73807B]">{t(action.description)}</p></Link>; })}</div></div><div className="rounded-2xl border border-[#DDD7CA] bg-[#173F43] p-5 text-white sm:p-6"><p className="ledger-label text-[#AEE0D3]">{t("Reporting chain")}</p><h3 className="mt-1 font-serif text-2xl">{t("Keep the handover moving.")}</h3><div className="mt-5 space-y-2.5">{Object.entries(data?.reports || {}).slice(0, 5).map(([key, value]) => <div className="flex items-center justify-between rounded-lg bg-white/[.08] px-3 py-2.5" key={key}><span className="text-sm capitalize text-[#E6F2EF]">{t(key.replaceAll("_", " "))}</span><StatusBadge status={value} /></div>)}</div><Link href="/reports" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#AEE0D3] hover:text-white">{t("Open reporting workspace")} <ArrowRight size={15} /></Link></div></section>
      <section className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><div className="overflow-hidden rounded-2xl border border-[#DDD7CA] bg-[#FFFDF8]"><div className="flex items-center justify-between border-b border-[#E7E1D6] px-5 py-4"><div><p className="ledger-label text-[#0F7667]">{t("Notifications")}</p><h3 className="font-serif text-xl text-[#214246]">{t("Signals needing attention")}</h3></div><Link href="/notifications" className="text-xs font-bold text-[#0F7667] hover:underline">{t("View all")}</Link></div><div className="divide-y divide-[#EAE4D9]">{data?.notifications.slice(0, 4).map((notification, index) => <div key={String(notification.id || index)} className="p-4"><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-[#D17837]" /><div><p className="text-sm font-semibold text-[#2A4A4D]">{formatDisplayValue(notification.title || notification.message, t("Operational notification"))}</p><p className="mt-1 text-xs leading-5 text-[#73817C]">{formatDisplayValue(notification.description || notification.created_at, t("Open the relevant operational workspace to review this operational signal."))}</p></div></div></div>)}{!data?.notifications.length && <p className="p-5 text-sm text-[#6F7D78]">{t("No unread operational signals are available.")}</p>}</div></div><div className="rounded-2xl border border-[#DDD7CA] bg-[#FFFDF8] p-5"><p className="ledger-label text-[#0F7667]">{t("Operational signal layers")}</p><h3 className="mt-1 font-serif text-xl text-[#214246]">{t("Trend endpoints, ready for your scope.")}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Attendance trend", "Issue categories", "Inspection quality"].map((label, index) => <div key={label} className="rounded-xl border border-[#E5DED3] bg-[#FAF8F2] p-4"><div className="flex h-16 items-end gap-1.5">{[32, 54, 38, 70, 58, 84, 66].map((height, bar) => <span key={bar} className="flex-1 rounded-t-sm bg-[#0F7667]" style={{ height: `${Math.max(10, height - index * 8)}%`, opacity: .3 + bar * .08 }} />)}</div><p className="mt-3 text-xs font-bold text-[#365356]">{t(label)}</p></div>)}</div></div></section>
    </div>}</AppShell>;
}
