/** Coastal Ledger account page: current identity, role context, password action, and transparent integration posture. */
import { KeyRound, ShieldCheck, UserRound } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { WorkspaceHeader, WorkflowNotice } from "@/components/WorkspacePrimitives";
import { useAuth } from "@/contexts/AuthContext";
import { API_BASE_URL } from "@/lib/api";
import { roleLabels } from "@/lib/navigation";
export default function ProfilePage() { const { user, permissions } = useAuth(); return <AppShell><WorkspaceHeader eyebrow="Account & security" title="Your operational identity." description="Review the role and API connection governing what you can see and do. Changes to role scope and passwords remain controlled by White Bird’s authenticated backend." /><div className="grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="rounded-2xl border border-[#DDD7CA] bg-[#FFFDF8] p-6"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#E3F0EC] text-[#0F7667]"><UserRound size={21} /></span><h3 className="mt-5 font-serif text-3xl text-[#1E4044]">{user?.full_name || user?.email}</h3><p className="mt-1 text-sm text-[#6D7B76]">{user?.email}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Platform role" value={roleLabels[user?.role || ""] || user?.role || "Assigned by policy"} /><Info label="Timezone" value={user?.timezone || "Set by your account"} /><Info label="Visible actions" value={permissions ? "Loaded from policy" : "Will load after API connection"} /><Info label="Session" value="Bearer access token" /></div></div><div className="space-y-5"><div className="rounded-2xl border border-[#DDD7CA] bg-[#0B3540] p-6 text-white"><KeyRound size={22} className="text-[#83CCBF]" /><h3 className="mt-5 font-serif text-2xl">Password and access tokens</h3><p className="mt-2 text-sm leading-6 text-[#C8DCD8]">Password change and personal API-token endpoints are recognised by the client foundation. Add the deployed API origin to enable these account controls.</p><div className="mt-5 inline-flex items-center gap-2 rounded-lg bg-white/[.09] px-3 py-2 text-xs text-[#C8DCD8]"><ShieldCheck size={15} className="text-[#83CCBF]" />Backend remains the source of authorization.</div></div><WorkflowNotice><strong>Integration target:</strong>&nbsp;{API_BASE_URL}. Production deployment should set `VITE_API_BASE_URL` to the public Django Ninja API base path and permit this frontend origin through CORS.</WorkflowNotice></div></div></AppShell>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#E7E1D6] bg-[#FCFAF6] p-3.5"><p className="ledger-label text-[#778680]">{label}</p><p className="mt-1 text-sm font-bold text-[#365457]">{value}</p></div>; }
