# Generated by Django 5.2.17 on 2026-08-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.site_management.validators


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneSupervisorAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_from", models.DateField(db_index=True)),
                ("assigned_to", models.DateField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Zone supervisor assignment",
                "verbose_name_plural": "Zone supervisor assignments",
                "ordering": ["zone__name", "user__email"],
            },
        ),
        migrations.AddField(
            model_name="site",
            name="building_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="site",
            name="contact_person",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="site",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="site",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="site",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="work_mode",
            field=models.CharField(
                choices=[("full_time", "Full Time"), ("shift", "Shift"), ("full_time_and_shift", "Full Time & Shift")],
                db_index=True,
                default="full_time",
                help_text="Manually configured staffing schedule model.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="working_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Working weekday codes (mon..sun), e.g. ["mon","tue"]. Portable ArrayField equivalent.',
                validators=[apps.site_management.validators.validate_working_days],
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="code",
            field=models.CharField(
                db_index=True, help_text="Unique site code (site_code).", max_length=12, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, help_text="Active/inactive operational flag."),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(help_text="Site name (site_name).", max_length=160),
        ),
        migrations.CreateModel(
            name="SiteSupervisorAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_from", models.DateField(db_index=True)),
                ("assigned_to", models.DateField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_primary", models.BooleanField(default=False, help_text="Primary supervisor of the site.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_assignments",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_supervisor_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site supervisor assignment",
                "verbose_name_plural": "Site supervisor assignments",
                "ordering": ["site__name", "user__email"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssistantGeneralSupervisorAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_from", models.DateField(db_index=True)),
                ("assigned_to", models.DateField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("all_zones", models.BooleanField(default=False, help_text="Covers every zone when true.")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ags_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ags_assignments",
                        to="site_management.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant general supervisor assignment",
                "verbose_name_plural": "Assistant general supervisor assignments",
                "ordering": ["user__email"],
            },
        ),
        migrations.AddField(
            model_name="site",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="site_management.zone",
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["zone", "is_active"], name="site_manage_zone_id_ef8529_idx"),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["work_mode", "is_active"], name="site_manage_work_mo_352066_idx"),
        ),
        migrations.AddField(
            model_name="zonesupervisorassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zonesupervisorassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zonesupervisorassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zone_supervisor_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zonesupervisorassignment",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_assignments",
                to="site_management.zone",
            ),
        ),
        migrations.AddIndex(
            model_name="sitesupervisorassignment",
            index=models.Index(fields=["user", "is_active"], name="site_manage_user_id_312b02_idx"),
        ),
        migrations.AddIndex(
            model_name="sitesupervisorassignment",
            index=models.Index(fields=["site", "is_active"], name="site_manage_site_id_601a4a_idx"),
        ),
        migrations.AddConstraint(
            model_name="sitesupervisorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)), fields=("site", "user"), name="uniq_active_site_supervisor"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["is_active", "name"], name="site_manage_is_acti_05f35f_idx"),
        ),
        migrations.AddConstraint(
            model_name="assistantgeneralsupervisorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)), fields=("user",), name="uniq_active_ags_assignment"
            ),
        ),
        migrations.AddIndex(
            model_name="zonesupervisorassignment",
            index=models.Index(fields=["user", "is_active"], name="site_manage_user_id_c92277_idx"),
        ),
        migrations.AddIndex(
            model_name="zonesupervisorassignment",
            index=models.Index(fields=["zone", "is_active"], name="site_manage_zone_id_4efdda_idx"),
        ),
        migrations.AddConstraint(
            model_name="zonesupervisorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)), fields=("zone", "user"), name="uniq_active_zone_supervisor"
            ),
        ),
    ]
