# Generated by Django 5.2.17 on 2026-08-14 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.site_management.validators


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0002_zonesupervisorassignment_site_building_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(db_index=True, max_length=24, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational role",
                "verbose_name_plural": "Operational roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SiteWorkingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_assignment_types",
                    models.JSONField(
                        blank=True, default=list, help_text="Configurable assignment type codes permitted at this site."
                    ),
                ),
                (
                    "attendance_locked",
                    models.BooleanField(default=False, help_text="Prevents attendance edits outside authorised flows."),
                ),
                (
                    "require_shift_area_assignment",
                    models.BooleanField(default=False, help_text="Staff must be assigned to both a shift and an area."),
                ),
                (
                    "allow_temporary_transfers",
                    models.BooleanField(default=False, help_text="Permits temporary staff transfers between sites."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_rule",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site working rule",
                "verbose_name_plural": "Site working rules",
            },
        ),
        migrations.CreateModel(
            name="SiteArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area_name", models.CharField(max_length=160)),
                ("area_code", models.CharField(blank=True, default="", max_length=16)),
                ("floor", models.CharField(blank=True, default="", max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="areas", to="site_management.site"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site area",
                "verbose_name_plural": "Site areas",
                "ordering": ["site__name", "area_name"],
                "indexes": [models.Index(fields=["site", "is_active"], name="site_manage_site_id_4408eb_idx")],
                "constraints": [models.UniqueConstraint(fields=("site", "area_name"), name="uniq_area_name_per_site")],
            },
        ),
        migrations.CreateModel(
            name="SiteShift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shift_name", models.CharField(max_length=160)),
                ("shift_code", models.CharField(blank=True, default="", max_length=16)),
                ("start_time", models.TimeField(db_index=True)),
                ("end_time", models.TimeField(db_index=True)),
                (
                    "effective_days",
                    models.JSONField(
                        default=list,
                        help_text="Day codes the shift runs (mon..sun). At least one required.",
                        validators=[apps.site_management.validators.validate_effective_days],
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0, help_text="Display order within the site.")),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shifts", to="site_management.site"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site shift",
                "verbose_name_plural": "Site shifts",
                "ordering": ["site__name", "sequence", "start_time"],
                "indexes": [models.Index(fields=["site", "is_active"], name="site_manage_site_id_fb6527_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("site", "shift_name"),
                        name="uniq_active_shift_name",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("shift_code__gt", "")),
                        fields=("site", "shift_code"),
                        name="uniq_active_shift_code",
                    ),
                ],
            },
        ),
    ]
