# Generated by Django 5.2.17 on 2026-08-14 04:57

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.validators
import apps.core.files


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0003_operationalrole_siteworkingrule_sitearea_siteshift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cleaner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("nida", "NIDA"),
                            ("zanzibar_id", "Zanzibar ID"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("id_number", models.CharField(db_index=True, max_length=64)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=16,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("living_location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default="", max_length=16, validators=[apps.accounts.validators.validate_phone]
                    ),
                ),
                ("near_person_name", models.CharField(blank=True, default="", max_length=150)),
                ("near_person_relationship", models.CharField(blank=True, default="", max_length=120)),
                (
                    "near_person_phone",
                    models.CharField(
                        blank=True, default="", max_length=16, validators=[apps.accounts.validators.validate_phone]
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=apps.core.files.PrivateMediaStorage(),
                        upload_to="cleaners/photos/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applicant", "Applicant"),
                            ("trainee", "Trainee"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="applicant",
                        max_length=16,
                    ),
                ),
                ("registration_date", models.DateField(db_index=True, default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaner",
                "verbose_name_plural": "Cleaners",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="CleanerDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Privately stored file; never exposed via a public URL.",
                        max_length=500,
                        storage=apps.core.files.PrivateMediaStorage(),
                        upload_to="private/%Y/%m/",
                    ),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=127)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("nida", "NIDA"),
                            ("zanzibar_id", "Zanzibar ID"),
                            ("profile_photo", "Profile Photo"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("document_number", models.CharField(blank=True, default="", max_length=64)),
                ("file_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("is_primary_id", models.BooleanField(default=False)),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="site_management.cleaner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaner document",
                "verbose_name_plural": "Cleaner documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cleaner",
            index=models.Index(fields=["status", "registration_date"], name="site_manage_status_ab1c56_idx"),
        ),
        migrations.AddConstraint(
            model_name="cleaner",
            constraint=models.UniqueConstraint(fields=("id_type", "id_number"), name="uniq_cleaner_id_type_number"),
        ),
        migrations.AddIndex(
            model_name="cleanerdocument",
            index=models.Index(fields=["cleaner", "status"], name="site_manage_cleaner_2eef26_idx"),
        ),
    ]
