# Generated by Django 5.2.17 on 2026-08-14 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0004_cleaner_cleanerdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanerSiteAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_type",
                    models.CharField(choices=[("full_time", "Full Time"), ("shift", "Shift")], max_length=16),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_assignments",
                        to="site_management.cleaner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaner_assignments",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaner site assignment",
                "verbose_name_plural": "Cleaner site assignments",
                "ordering": ["-start_date", "cleaner__last_name"],
            },
        ),
        migrations.CreateModel(
            name="CleanerShiftAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaner_assignments",
                        to="site_management.siteshift",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="site_management.cleanersiteassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaner shift assignment",
                "verbose_name_plural": "Cleaner shift assignments",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="CleanerAreaSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operational_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="area_schedules",
                        to="site_management.operationalrole",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="area_schedules",
                        to="site_management.siteshift",
                    ),
                ),
                (
                    "site_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_schedules",
                        to="site_management.sitearea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_schedules",
                        to="site_management.cleanersiteassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaner area schedule",
                "verbose_name_plural": "Cleaner area schedules",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="cleanersiteassignment",
            index=models.Index(fields=["site", "status", "assignment_type"], name="site_manage_site_id_b31586_idx"),
        ),
        migrations.AddConstraint(
            model_name="cleanersiteassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["active", "suspended"])),
                fields=("cleaner", "site"),
                name="uniq_active_cleaner_site_assignment",
            ),
        ),
        migrations.AddIndex(
            model_name="cleanershiftassignment",
            index=models.Index(fields=["assignment", "is_active"], name="site_manage_assignm_e00d6a_idx"),
        ),
        migrations.AddConstraint(
            model_name="cleanershiftassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("assignment", "shift"),
                name="uniq_active_assignment_shift",
            ),
        ),
        migrations.AddIndex(
            model_name="cleanerareaschedule",
            index=models.Index(fields=["site_area", "date"], name="site_manage_site_ar_d5c756_idx"),
        ),
        migrations.AddIndex(
            model_name="cleanerareaschedule",
            index=models.Index(fields=["assignment", "date"], name="site_manage_assignm_c5e128_idx"),
        ),
        migrations.AddIndex(
            model_name="cleanerareaschedule",
            index=models.Index(fields=["date", "is_active"], name="site_manage_date_a588ef_idx"),
        ),
    ]
