# Generated by Django 5.2.17 on 2026-08-14 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0005_cleanersiteassignment_cleanershiftassignment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("sick", "Sick"),
                            ("leave", "Leave"),
                            ("permission", "Permission"),
                            ("off", "Off"),
                            ("not_scheduled", "Not Scheduled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("returned", "Returned"),
                            ("locked", "Locked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("return_reason", models.TextField(blank=True, default="")),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="site_management.cleaner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="site_management.siteshift",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance record",
                "verbose_name_plural": "Attendance records",
                "ordering": ["attendance_date", "site__name", "cleaner__last_name"],
                "indexes": [
                    models.Index(fields=["site", "attendance_date"], name="site_manage_site_id_7b1f8e_idx"),
                    models.Index(fields=["site", "attendance_date", "shift"], name="site_manage_site_id_c4709f_idx"),
                    models.Index(fields=["cleaner", "attendance_date"], name="site_manage_cleaner_fd175f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("shift__isnull", True)),
                        fields=("cleaner", "site", "attendance_date"),
                        name="uniq_attendance_ft_per_day",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("shift__isnull", False)),
                        fields=("cleaner", "site", "shift", "attendance_date"),
                        name="uniq_attendance_shift_per_day",
                    ),
                ],
            },
        ),
    ]
