# Generated by Django 5.2.17 on 2026-08-14 07:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0006_attendancerecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TraineeProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(db_index=True)),
                ("expected_end_date", models.DateField()),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_training", "In Training"),
                            ("extended", "Extended"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="in_training",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_site_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_trainees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_programs",
                        to="site_management.cleaner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_programs",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainee program",
                "verbose_name_plural": "Trainee programs",
                "ordering": ["-start_date", "cleaner__last_name"],
            },
        ),
        migrations.CreateModel(
            name="TraineeEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("evaluation_date", models.DateField(db_index=True)),
                (
                    "attendance_score",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "performance_score",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "behavior_score",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "skill_score",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MaxValueValidator(400)]
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Final evaluation required before a trainee can pass."
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainee_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainee_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="site_management.traineeprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainee evaluation",
                "verbose_name_plural": "Trainee evaluations",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.AddIndex(
            model_name="traineeprogram",
            index=models.Index(fields=["site", "status"], name="site_manage_site_id_d88b93_idx"),
        ),
        migrations.AddConstraint(
            model_name="traineeprogram",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["in_training", "extended"])),
                fields=("cleaner",),
                name="uniq_active_trainee_program",
            ),
        ),
    ]
