# Generated by Django 5.2.17 on 2026-08-14 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0007_traineeprogram_traineeevaluation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("store_name", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stores", to="site_management.site"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site store",
                "verbose_name_plural": "Site stores",
                "ordering": ["site__name", "store_name"],
            },
        ),
        migrations.CreateModel(
            name="StockRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("zone_reviewed", "Zone Reviewed"),
                            ("office_processed", "Office Processed"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_stock_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_requests",
                        to="site_management.site",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="site_management.sitestore",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock request",
                "verbose_name_plural": "Stock requests",
                "ordering": ["-request_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("item_name", models.CharField(max_length=160)),
                ("item_code", models.CharField(blank=True, default="", max_length=32)),
                ("unit", models.CharField(default="piece", max_length=32)),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("opening_stock", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("current_stock", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("minimum_stock_level", models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="site_management.sitestore",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store item",
                "verbose_name_plural": "Store items",
                "ordering": ["store__store_name", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="StockRequestItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("approved_quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="site_management.stockrequest",
                    ),
                ),
                (
                    "store_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_request_items",
                        to="site_management.storeitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock request item",
                "verbose_name_plural": "Stock request items",
                "ordering": ["request", "store_item__item_name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening"),
                            ("received", "Received"),
                            ("issued", "Issued"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("adjustment", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("movement_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="site_management.sitearea",
                    ),
                ),
                (
                    "cleaner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="site_management.cleaner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="site_management.storeitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock movement",
                "verbose_name_plural": "Stock movements",
                "ordering": ["-movement_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sitestore",
            index=models.Index(fields=["site", "is_active"], name="site_manage_site_id_cc3649_idx"),
        ),
        migrations.AddIndex(
            model_name="stockrequest",
            index=models.Index(fields=["site", "status"], name="site_manage_site_id_9d8e40_idx"),
        ),
        migrations.AddIndex(
            model_name="stockrequest",
            index=models.Index(fields=["store", "status"], name="site_manage_store_i_1f5f42_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["store", "is_active"], name="site_manage_store_i_9e363f_idx"),
        ),
        migrations.AddConstraint(
            model_name="storeitem",
            constraint=models.UniqueConstraint(fields=("store", "item_name"), name="uniq_store_item_name"),
        ),
        migrations.AddConstraint(
            model_name="storeitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_code__gt", "")), fields=("store", "item_code"), name="uniq_store_item_code"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["store_item", "movement_date"], name="site_manage_store_i_e67784_idx"),
        ),
    ]
