# Generated by Django 5.2.17 on 2026-08-14 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.files


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0008_sitestore_stockrequest_storeitem_stockrequestitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("template_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_templates",
                        to="site_management.sitearea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_templates",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection template",
                "verbose_name_plural": "Inspection templates",
                "ordering": ["template_name"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspection_date", models.DateField(db_index=True)),
                (
                    "overall_status",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "Passed"), ("failed", "Failed"), ("needs_attention", "Needs Attention")],
                        db_index=True,
                        default="",
                        max_length=20,
                    ),
                ),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="site_management.sitearea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_site_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="site_management.siteshift",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="site_management.inspectiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionTemplateItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_label", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes/No"),
                            ("pass_fail", "Pass/Fail"),
                            ("score", "Score"),
                            ("text", "Text"),
                            ("photo", "Photo"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                ("help_text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="site_management.inspectiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection template item",
                "verbose_name_plural": "Inspection template items",
                "ordering": ["template", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Privately stored file; never exposed via a public URL.",
                        max_length=500,
                        storage=apps.core.files.PrivateMediaStorage(),
                        upload_to="private/%Y/%m/",
                    ),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=127)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("value_text", models.TextField(blank=True, default="")),
                ("value_number", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="site_management.inspection",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="site_management.inspectiontemplateitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection result",
                "verbose_name_plural": "Inspection results",
                "ordering": ["template_item__sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="inspectiontemplate",
            index=models.Index(fields=["site", "is_active"], name="site_manage_site_id_76dfe9_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["site", "status"], name="site_manage_site_id_34c7c0_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["area", "inspection_date"], name="site_manage_area_id_56e0fc_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["template", "inspection_date"], name="site_manage_templat_69427d_idx"),
        ),
        migrations.AddConstraint(
            model_name="inspectiontemplateitem",
            constraint=models.UniqueConstraint(fields=("template", "sequence"), name="uniq_template_item_sequence"),
        ),
        migrations.AddConstraint(
            model_name="inspectionresult",
            constraint=models.UniqueConstraint(
                fields=("inspection", "template_item"), name="uniq_inspection_template_item"
            ),
        ),
    ]
