# Generated by Django 5.2.17 on 2026-08-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0010_issue_job_issue_site_manage_site_id_59feda_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantGeneralSummaryReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(db_index=True)),
                ("zone_ids", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("problems_extracted", models.JSONField(blank=True, default=list)),
                ("recommendations", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("returned", "Returned"),
                            ("general_reviewed", "General Reviewed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant_general_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_reports_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant general summary report",
                "verbose_name_plural": "Assistant general summary reports",
                "ordering": ["-report_date"],
                "constraints": [models.UniqueConstraint(fields=("report_date",), name="uniq_assistant_report")],
            },
        ),
        migrations.CreateModel(
            name="DailySiteReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(db_index=True)),
                ("attendance_summary", models.JSONField(blank=True, default=dict)),
                ("store_summary", models.JSONField(blank=True, default=dict)),
                ("inspection_summary", models.JSONField(blank=True, default=dict)),
                ("trainee_summary", models.JSONField(blank=True, default=dict)),
                ("issues_summary", models.JSONField(blank=True, default=dict)),
                ("general_comments", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("returned", "Returned"),
                            ("zone_reviewed", "Zone Reviewed"),
                            ("assistant_reviewed", "Assistant Reviewed"),
                            ("general_approved", "General Approved"),
                            ("management_submitted", "Management Submitted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("returned_reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="site_management.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily site report",
                "verbose_name_plural": "Daily site reports",
                "ordering": ["-report_date", "site__name"],
                "indexes": [
                    models.Index(fields=["site", "report_date", "status"], name="site_manage_site_id_01c1eb_idx")
                ],
                "constraints": [models.UniqueConstraint(fields=("site", "report_date"), name="uniq_daily_site_report")],
            },
        ),
        migrations.CreateModel(
            name="GeneralManagementReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(db_index=True)),
                ("final_summary", models.TextField(blank=True, default="")),
                ("key_issues", models.JSONField(blank=True, default=list)),
                ("assigned_jobs", models.JSONField(blank=True, default=list)),
                ("recommendations", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted_to_management", "Submitted to Management")],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "general_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_reports_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "General management report",
                "verbose_name_plural": "General management reports",
                "ordering": ["-report_date"],
                "constraints": [models.UniqueConstraint(fields=("report_date",), name="uniq_general_report")],
            },
        ),
        migrations.CreateModel(
            name="ZoneSummaryReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(db_index=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("issues_extracted", models.JSONField(blank=True, default=list)),
                ("site_reports", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("returned", "Returned"),
                            ("assistant_reviewed", "Assistant Reviewed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_reports",
                        to="site_management.zone",
                    ),
                ),
                (
                    "zone_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zone_reports_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone summary report",
                "verbose_name_plural": "Zone summary reports",
                "ordering": ["-report_date", "zone__name"],
                "constraints": [models.UniqueConstraint(fields=("zone", "report_date"), name="uniq_zone_report")],
            },
        ),
    ]
