# Generated by Django 5.2.17 on 2026-08-14 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0011_assistantgeneralsummaryreport_dailysitereport_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assistantgeneralsummaryreport",
            index=models.Index(fields=["report_date", "status"], name="site_manage_report__bdc040_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["attendance_date", "status"], name="site_manage_attenda_93e2e7_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["site", "attendance_date", "status"], name="site_manage_site_id_c54d3b_idx"),
        ),
        migrations.AddIndex(
            model_name="cleanerdocument",
            index=models.Index(fields=["status", "document_type"], name="site_manage_status_122e9d_idx"),
        ),
        migrations.AddIndex(
            model_name="cleanerdocument",
            index=models.Index(fields=["cleaner", "status", "document_type"], name="site_manage_cleaner_8bc6d4_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysitereport",
            index=models.Index(fields=["report_date", "status"], name="site_manage_report__d48549_idx"),
        ),
        migrations.AddIndex(
            model_name="generalmanagementreport",
            index=models.Index(fields=["report_date", "status"], name="site_manage_report__6fe389_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["status", "priority", "due_date"], name="site_manage_status_b92cf4_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["site", "created_at"], name="site_manage_site_id_41a6c6_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["assigned_to_user", "status"], name="site_manage_assigne_83835b_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["site", "created_at"], name="site_manage_site_id_82e20a_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["store", "current_stock"], name="site_manage_store_i_60e542_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["current_stock", "minimum_stock_level"], name="site_manage_current_2785af_idx"),
        ),
        migrations.AddIndex(
            model_name="zonesummaryreport",
            index=models.Index(fields=["report_date", "status"], name="site_manage_report__50a10c_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True), name="ck_stockmovement_nonzero"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_quantity__gt", 0)), name="ck_stockrequestitem_requested_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("approved_quantity__gte", 0), ("approved_quantity__isnull", True), _connector="OR"),
                name="ck_stockrequestitem_approved_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="storeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_stock__gte", 0)), name="ck_storeitem_opening_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock_level__gte", 0)), name="ck_storeitem_min_nonneg"
            ),
        ),
    ]
