# Generated by Django 5.2.17 on 2026-08-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0014_reportdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrequestitem",
            name="quantity_left",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="stockrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_left__gte", 0)), name="ck_stockrequestitem_left_nonneg"
            ),
        ),
    ]
