# Generated by Django 5.2.17 on 2026-08-15 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_management", "0016_inspectionresult_responsible_cleaner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIOptimizationBrief",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brief_type",
                    models.CharField(
                        choices=[
                            ("on_demand", "On demand"),
                            ("daily", "Daily leadership brief"),
                            ("weekly", "Friday weekly optimization brief"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("scope_key", models.CharField(db_index=True, max_length=160)),
                ("role", models.CharField(db_index=True, max_length=64)),
                ("evidence_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(default="deepseek", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=96)),
                ("error_message", models.TextField(blank=True, default="")),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI optimization brief",
                "verbose_name_plural": "AI optimization briefs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["brief_type", "report_date", "scope_key"], name="site_manage_brief_t_19e0d1_idx"
                    ),
                    models.Index(fields=["status", "created_at"], name="site_manage_status_4e3c22_idx"),
                ],
            },
        ),
    ]
