# Generated by Django 5.2.17 on 2026-08-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0027_conversation_conversationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisortimetableentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
