# Generated by Django 5.2.17 on 2026-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0028_timetable_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorchecklistsubmission',
            name='shift_slot',
            field=models.CharField(choices=[('asubuhi', 'ASUBUHI'), ('mchana', 'MCHANA'), ('full_day', 'FULL DAY')], max_length=16),
        ),
        migrations.AlterField(
            model_name='supervisortimetableentry',
            name='shift_slot',
            field=models.CharField(choices=[('asubuhi', 'ASUBUHI'), ('mchana', 'MCHANA'), ('full_day', 'FULL DAY')], max_length=16),
        ),
    ]
