# Generated by Django 5.2.17 on 2026-08-20 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0029_full_day_timetable_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assistantgeneralsupervisorassignment',
            name='uniq_active_ags_assignment',
        ),
        migrations.AddConstraint(
            model_name='assistantgeneralsupervisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'zone'), name='uniq_active_ags_user_zone'),
        ),
        migrations.AddConstraint(
            model_name='assistantgeneralsupervisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('all_zones', True), ('is_active', True)), fields=('user',), name='uniq_active_ags_all_zones'),
        ),
    ]
