# Generated by Django 5.2.17 on 2026-08-20 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0030_ags_multi_zone_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product_name', models.CharField(max_length=160)),
                ('product_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('unit', models.CharField(default='piece', max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('current_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Company product',
                'verbose_name_plural': 'Company products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('zone_verified', 'Zone Verified'), ('assistant_approved', 'Assistant Approved'), ('hr_packed', 'HR Packed'), ('assembled', 'Assembled'), ('rejected', 'Rejected')], max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Stock request approval',
                'verbose_name_plural': 'Stock request approvals',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transfer_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Stock transfer',
                'verbose_name_plural': 'Stock transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreMonthlyOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_month', models.DateField(db_index=True)),
                ('opening_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Store monthly opening',
                'verbose_name_plural': 'Store monthly openings',
                'ordering': ['-opening_month', 'store_item__item_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitestore',
            options={'ordering': ['store_type', 'store_name'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AddField(
            model_name='sitestore',
            name='parent_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_stores', to='site_management.sitestore'),
        ),
        migrations.AddField(
            model_name='sitestore',
            name='store_type',
            field=models.CharField(choices=[('super', 'Super Store'), ('power', 'Power Store'), ('site', 'Site Store')], db_index=True, default='site', max_length=16),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='request_month',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='assistant_approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='packed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='verified_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sitestore',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='site_management.site'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('received', 'Received'), ('issued', 'Issued'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('adjustment', 'Adjustment')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('zone_reviewed', 'Zone Reviewed'), ('zone_verified', 'Zone Verified'), ('assistant_approved', 'Assistant Approved'), ('hr_packing', 'HR Packing'), ('assembled', 'Assembled'), ('office_processed', 'Office Processed'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sitestore',
            index=models.Index(fields=['parent_store', 'is_active'], name='site_manage_parent__b40c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='sitestore',
            index=models.Index(fields=['store_type', 'is_active'], name='site_manage_store_t_9534fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['request_month', 'status'], name='site_manage_request_d24ddc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('verified_quantity__gte', 0), ('verified_quantity__isnull', True), _connector='OR'), name='ck_stockrequestitem_verified_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('assistant_approved_quantity__gte', 0), ('assistant_approved_quantity__isnull', True), _connector='OR'), name='ck_stockrequestitem_assistant_approved_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('packed_quantity__gte', 0), ('packed_quantity__isnull', True), _connector='OR'), name='ck_stockrequestitem_packed_nonneg'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_items', to='site_management.companyproduct'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_storeitem_cost_nonneg'),
        ),
        migrations.AddField(
            model_name='stockrequestapproval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequestapproval',
            name='decision_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_request_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequestapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='site_management.stockrequest'),
        ),
        migrations.AddField(
            model_name='stockrequestapproval',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='site_management.storeitem'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='site_management.sitestore'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='site_management.companyproduct'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='site_management.storeitem'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='site_management.sitestore'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='site_management.stocktransfer'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_stockmovement_cost_nonneg'),
        ),
        migrations.AddField(
            model_name='storemonthlyopening',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storemonthlyopening',
            name='opening_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_opening_record', to='site_management.stockmovement'),
        ),
        migrations.AddField(
            model_name='storemonthlyopening',
            name='store_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_openings', to='site_management.storeitem'),
        ),
        migrations.AddField(
            model_name='storemonthlyopening',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companyproduct',
            constraint=models.CheckConstraint(condition=models.Q(('current_unit_cost__gte', 0)), name='ck_companyproduct_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestapproval',
            constraint=models.UniqueConstraint(fields=('request', 'stage'), name='uniq_stockrequest_approval_stage'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['source_store', 'transfer_date'], name='site_manage_source__7ea5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination_store', 'transfer_date'], name='site_manage_destina_f7348c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_stocktransfer_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_stocktransfer_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storemonthlyopening',
            constraint=models.UniqueConstraint(fields=('store_item', 'opening_month'), name='uniq_store_monthly_opening'),
        ),
        migrations.AddConstraint(
            model_name='storemonthlyopening',
            constraint=models.CheckConstraint(condition=models.Q(('opening_quantity__gte', 0)), name='ck_storeopening_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storemonthlyopening',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_storeopening_cost_nonneg'),
        ),
    ]
